/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */
import * as zod from 'zod';


/**
 * @summary Adicionar check list
 */
export const addCheckListDevolucaoMobileParams = zod.object({
  "demandaId": zod.string()
})

export const addCheckListDevolucaoMobileBody = zod.object({
  "fotoBauAberto": zod.instanceof(File).describe('Foto do baú fechado'),
  "fotoBauFechado": zod.instanceof(File).describe('Foto do baú fechado'),
  "demandaId": zod.string(),
  "temperaturaBau": zod.string().describe('Temperatura do Baú'),
  "temperaturaProduto": zod.string().describe('Temperatura do Produto'),
  "anomalias": zod.string().optional()
})

export const addCheckListDevolucaoMobileResponse = zod.string()

/**
 * @summary Listar demandas em aberto
 */
export const listarDemandasEmAbertoDevolucaoMobileParams = zod.object({
  "centerId": zod.string()
})

export const listarDemandasEmAbertoDevolucaoMobileResponseIdMin = -2147483648;
export const listarDemandasEmAbertoDevolucaoMobileResponseIdMax = 2147483647;export const listarDemandasEmAbertoDevolucaoMobileResponseQuantidadePaletesMinOne = -2147483648;
export const listarDemandasEmAbertoDevolucaoMobileResponseQuantidadePaletesMaxOne = 2147483647;

export const listarDemandasEmAbertoDevolucaoMobileResponseItem = zod.object({
  "id": zod.number().min(listarDemandasEmAbertoDevolucaoMobileResponseIdMin).max(listarDemandasEmAbertoDevolucaoMobileResponseIdMax),
  "placa": zod.string(),
  "motorista": zod.string(),
  "idTransportadora": zod.union([zod.string(),zod.null()]),
  "telefone": zod.union([zod.string(),zod.null()]),
  "cargaSegregada": zod.boolean(),
  "quantidadePaletes": zod.union([zod.number().min(listarDemandasEmAbertoDevolucaoMobileResponseQuantidadePaletesMinOne).max(listarDemandasEmAbertoDevolucaoMobileResponseQuantidadePaletesMaxOne),zod.null()]),
  "doca": zod.union([zod.string(),zod.null()]),
  "centerId": zod.string(),
  "adicionadoPorId": zod.string(),
  "conferenteId": zod.union([zod.string(),zod.null()]),
  "criadoEm": zod.string(),
  "atualizadoEm": zod.string(),
  "status": zod.enum(['AGUARDANDO_LIBERACAO', 'AGUARDANDO_CONFERENCIA', 'EM_CONFERENCIA', 'CONFERENCIA_FINALIZADA', 'FINALIZADO', 'CANCELADO']),
  "fechouComAnomalia": zod.union([zod.boolean(),zod.null()]),
  "liberadoParaConferenciaEm": zod.union([zod.string(),zod.null()]),
  "inicioConferenciaEm": zod.union([zod.string(),zod.null()]),
  "fimConferenciaEm": zod.union([zod.string(),zod.null()]),
  "finalizadoEm": zod.union([zod.string(),zod.null()]),
  "senha": zod.string(),
  "viagemId": zod.union([zod.string(),zod.null()])
})
export const listarDemandasEmAbertoDevolucaoMobileResponse = zod.array(listarDemandasEmAbertoDevolucaoMobileResponseItem)

/**
 * @summary Iniciar conferência
 */
export const startDemandaDevolucaoMobileBody = zod.object({
  "demandaId": zod.number(),
  "doca": zod.string()
})

export const startDemandaDevolucaoMobileResponseItem = zod.object({
  "demandaId": zod.number(),
  "sku": zod.string(),
  "descricao": zod.string(),
  "tipo": zod.enum(['CONTABIL', 'FISICO']),
  "tipoDevolucao": zod.enum(['RETORNO', 'REENTREGA']),
  "quantidadeCaixas": zod.number(),
  "quantidadeUnidades": zod.number(),
  "avariaCaixas": zod.number(),
  "avariaUnidades": zod.number()
})
export const startDemandaDevolucaoMobileResponse = zod.array(startDemandaDevolucaoMobileResponseItem)

/**
 * @summary Iniciar conferência
 */
export const addContagemCegaParams = zod.object({
  "demandaId": zod.string()
})

export const addContagemCegaBodyQuantidadeCaixasDefault = 0;export const addContagemCegaBodyQuantidadeUnidadesDefault = 0;

export const addContagemCegaBodyItem = zod.object({
  "descricao": zod.string(),
  "sku": zod.string(),
  "quantidadeCaixas": zod.number().optional(),
  "quantidadeUnidades": zod.number().optional(),
  "lote": zod.string()
})
export const addContagemCegaBody = zod.array(addContagemCegaBodyItem)

/**
 * @summary Finalizar demanda
 */
export const finalizarDemandaDevolucaoMobileParams = zod.object({
  "demandaId": zod.string()
})

/**
 * @summary Listar itens contabilizados
 */
export const getItensContabilDevolucaoMobileParams = zod.object({
  "demandaId": zod.string()
})

export const getItensContabilDevolucaoMobileResponseItem = zod.object({
  "demandaId": zod.number(),
  "sku": zod.string(),
  "descricao": zod.string(),
  "tipo": zod.enum(['CONTABIL', 'FISICO']),
  "tipoDevolucao": zod.enum(['RETORNO', 'REENTREGA']),
  "quantidadeCaixas": zod.number(),
  "quantidadeUnidades": zod.number(),
  "avariaCaixas": zod.number(),
  "avariaUnidades": zod.number()
})
export const getItensContabilDevolucaoMobileResponse = zod.array(getItensContabilDevolucaoMobileResponseItem)

/**
 * @summary Pegar Status pelo ID
 */
export const getStatusByIdParams = zod.object({
  "demandaId": zod.string()
})

export const getStatusByIdResponse = zod.string()

/**
 * @summary Adicionar anomalia de devolução
 */
export const addAnomaliaDevolucaoBody = zod.object({
  "demandaId": zod.number().describe('ID da demanda de devolução'),
  "sku": zod.string().describe('Código SKU do produto'),
  "descricao": zod.string().describe('Descrição da anomalia'),
  "lote": zod.string().describe('Lote do produto'),
  "tipo": zod.string().describe('Tipo da anomalia'),
  "natureza": zod.string().describe('Natureza da anomalia'),
  "causa": zod.string().describe('Causa da anomalia'),
  "tratado": zod.boolean().optional().describe('Indica se a anomalia já foi tratada'),
  "quantidadeCaixas": zod.number().describe('Quantidade de caixas afetadas'),
  "quantidadeUnidades": zod.number().describe('Quantidade de unidades afetadas'),
  "imagens": zod.array(zod.string()).describe('Lista de URLs ou identificadores das imagens')
})

