/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AddCheckListDto,
  AddConferenciaCegaDto,
  AnomaliaDevolucaoDto,
  ItensContabilDto,
  ListarDemandasDto,
  StartDemandaDto
} from '../../model';

import { axiosFetcher } from '../../../http/axios.http';
import type { ErrorType , BodyType } from '../../../http/axios.http';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Adicionar check list
 */
export const addCheckListDevolucaoMobile = (
    demandaId: string,
    addCheckListDto: BodyType<AddCheckListDto>,
 options?: SecondParameter<typeof axiosFetcher>,signal?: AbortSignal
) => {
      
      const formData = new FormData();
formData.append(`fotoBauAberto`, addCheckListDto.fotoBauAberto)
formData.append(`fotoBauFechado`, addCheckListDto.fotoBauFechado)
formData.append(`demandaId`, addCheckListDto.demandaId)
formData.append(`temperaturaBau`, addCheckListDto.temperaturaBau)
formData.append(`temperaturaProduto`, addCheckListDto.temperaturaProduto)
if(addCheckListDto.anomalias !== undefined) {
 formData.append(`anomalias`, addCheckListDto.anomalias)
 }

      return axiosFetcher<string>(
      {url: `/api/devolucao-mobile/add-check-list/${demandaId}`, method: 'POST',
      headers: {'Content-Type': 'multipart/form-data', },
       data: formData, signal
    },
      options);
    }
  


export const getAddCheckListDevolucaoMobileMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addCheckListDevolucaoMobile>>, TError,{demandaId: string;data: BodyType<AddCheckListDto>}, TContext>, request?: SecondParameter<typeof axiosFetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof addCheckListDevolucaoMobile>>, TError,{demandaId: string;data: BodyType<AddCheckListDto>}, TContext> => {

const mutationKey = ['addCheckListDevolucaoMobile'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addCheckListDevolucaoMobile>>, {demandaId: string;data: BodyType<AddCheckListDto>}> = (props) => {
          const {demandaId,data} = props ?? {};

          return  addCheckListDevolucaoMobile(demandaId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AddCheckListDevolucaoMobileMutationResult = NonNullable<Awaited<ReturnType<typeof addCheckListDevolucaoMobile>>>
    export type AddCheckListDevolucaoMobileMutationBody = BodyType<AddCheckListDto>
    export type AddCheckListDevolucaoMobileMutationError = ErrorType<unknown>

    /**
 * @summary Adicionar check list
 */
export const useAddCheckListDevolucaoMobile = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addCheckListDevolucaoMobile>>, TError,{demandaId: string;data: BodyType<AddCheckListDto>}, TContext>, request?: SecondParameter<typeof axiosFetcher>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof addCheckListDevolucaoMobile>>,
        TError,
        {demandaId: string;data: BodyType<AddCheckListDto>},
        TContext
      > => {

      const mutationOptions = getAddCheckListDevolucaoMobileMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Listar demandas em aberto
 */
export const listarDemandasEmAbertoDevolucaoMobile = (
    centerId: string,
 options?: SecondParameter<typeof axiosFetcher>,signal?: AbortSignal
) => {
      
      
      return axiosFetcher<ListarDemandasDto[]>(
      {url: `/api/devolucao-mobile/listar-demandas-em-aberto/${centerId}`, method: 'GET', signal
    },
      options);
    }
  



export const getListarDemandasEmAbertoDevolucaoMobileQueryKey = (centerId?: string,) => {
    return [
    `/api/devolucao-mobile/listar-demandas-em-aberto/${centerId}`
    ] as const;
    }

    
export const getListarDemandasEmAbertoDevolucaoMobileQueryOptions = <TData = Awaited<ReturnType<typeof listarDemandasEmAbertoDevolucaoMobile>>, TError = ErrorType<unknown>>(centerId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listarDemandasEmAbertoDevolucaoMobile>>, TError, TData>>, request?: SecondParameter<typeof axiosFetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListarDemandasEmAbertoDevolucaoMobileQueryKey(centerId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listarDemandasEmAbertoDevolucaoMobile>>> = ({ signal }) => listarDemandasEmAbertoDevolucaoMobile(centerId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(centerId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listarDemandasEmAbertoDevolucaoMobile>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListarDemandasEmAbertoDevolucaoMobileQueryResult = NonNullable<Awaited<ReturnType<typeof listarDemandasEmAbertoDevolucaoMobile>>>
export type ListarDemandasEmAbertoDevolucaoMobileQueryError = ErrorType<unknown>


export function useListarDemandasEmAbertoDevolucaoMobile<TData = Awaited<ReturnType<typeof listarDemandasEmAbertoDevolucaoMobile>>, TError = ErrorType<unknown>>(
 centerId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listarDemandasEmAbertoDevolucaoMobile>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listarDemandasEmAbertoDevolucaoMobile>>,
          TError,
          Awaited<ReturnType<typeof listarDemandasEmAbertoDevolucaoMobile>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosFetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListarDemandasEmAbertoDevolucaoMobile<TData = Awaited<ReturnType<typeof listarDemandasEmAbertoDevolucaoMobile>>, TError = ErrorType<unknown>>(
 centerId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listarDemandasEmAbertoDevolucaoMobile>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listarDemandasEmAbertoDevolucaoMobile>>,
          TError,
          Awaited<ReturnType<typeof listarDemandasEmAbertoDevolucaoMobile>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListarDemandasEmAbertoDevolucaoMobile<TData = Awaited<ReturnType<typeof listarDemandasEmAbertoDevolucaoMobile>>, TError = ErrorType<unknown>>(
 centerId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listarDemandasEmAbertoDevolucaoMobile>>, TError, TData>>, request?: SecondParameter<typeof axiosFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Listar demandas em aberto
 */

export function useListarDemandasEmAbertoDevolucaoMobile<TData = Awaited<ReturnType<typeof listarDemandasEmAbertoDevolucaoMobile>>, TError = ErrorType<unknown>>(
 centerId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listarDemandasEmAbertoDevolucaoMobile>>, TError, TData>>, request?: SecondParameter<typeof axiosFetcher>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListarDemandasEmAbertoDevolucaoMobileQueryOptions(centerId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Iniciar conferência
 */
export const startDemandaDevolucaoMobile = (
    startDemandaDto: BodyType<StartDemandaDto>,
 options?: SecondParameter<typeof axiosFetcher>,signal?: AbortSignal
) => {
      
      
      return axiosFetcher<ItensContabilDto[]>(
      {url: `/api/devolucao-mobile/start-demanda`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: startDemandaDto, signal
    },
      options);
    }
  


export const getStartDemandaDevolucaoMobileMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof startDemandaDevolucaoMobile>>, TError,{data: BodyType<StartDemandaDto>}, TContext>, request?: SecondParameter<typeof axiosFetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof startDemandaDevolucaoMobile>>, TError,{data: BodyType<StartDemandaDto>}, TContext> => {

const mutationKey = ['startDemandaDevolucaoMobile'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof startDemandaDevolucaoMobile>>, {data: BodyType<StartDemandaDto>}> = (props) => {
          const {data} = props ?? {};

          return  startDemandaDevolucaoMobile(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type StartDemandaDevolucaoMobileMutationResult = NonNullable<Awaited<ReturnType<typeof startDemandaDevolucaoMobile>>>
    export type StartDemandaDevolucaoMobileMutationBody = BodyType<StartDemandaDto>
    export type StartDemandaDevolucaoMobileMutationError = ErrorType<unknown>

    /**
 * @summary Iniciar conferência
 */
export const useStartDemandaDevolucaoMobile = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof startDemandaDevolucaoMobile>>, TError,{data: BodyType<StartDemandaDto>}, TContext>, request?: SecondParameter<typeof axiosFetcher>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof startDemandaDevolucaoMobile>>,
        TError,
        {data: BodyType<StartDemandaDto>},
        TContext
      > => {

      const mutationOptions = getStartDemandaDevolucaoMobileMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Iniciar conferência
 */
export const addContagemCega = (
    demandaId: string,
    addConferenciaCegaDto: BodyType<AddConferenciaCegaDto[]>,
 options?: SecondParameter<typeof axiosFetcher>,signal?: AbortSignal
) => {
      
      
      return axiosFetcher<void>(
      {url: `/api/devolucao-mobile/add-contagem-cega/${demandaId}`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addConferenciaCegaDto, signal
    },
      options);
    }
  


export const getAddContagemCegaMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addContagemCega>>, TError,{demandaId: string;data: BodyType<AddConferenciaCegaDto[]>}, TContext>, request?: SecondParameter<typeof axiosFetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof addContagemCega>>, TError,{demandaId: string;data: BodyType<AddConferenciaCegaDto[]>}, TContext> => {

const mutationKey = ['addContagemCega'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addContagemCega>>, {demandaId: string;data: BodyType<AddConferenciaCegaDto[]>}> = (props) => {
          const {demandaId,data} = props ?? {};

          return  addContagemCega(demandaId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AddContagemCegaMutationResult = NonNullable<Awaited<ReturnType<typeof addContagemCega>>>
    export type AddContagemCegaMutationBody = BodyType<AddConferenciaCegaDto[]>
    export type AddContagemCegaMutationError = ErrorType<unknown>

    /**
 * @summary Iniciar conferência
 */
export const useAddContagemCega = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addContagemCega>>, TError,{demandaId: string;data: BodyType<AddConferenciaCegaDto[]>}, TContext>, request?: SecondParameter<typeof axiosFetcher>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof addContagemCega>>,
        TError,
        {demandaId: string;data: BodyType<AddConferenciaCegaDto[]>},
        TContext
      > => {

      const mutationOptions = getAddContagemCegaMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Finalizar demanda
 */
export const finalizarDemandaDevolucaoMobile = (
    demandaId: string,
 options?: SecondParameter<typeof axiosFetcher>,signal?: AbortSignal
) => {
      
      
      return axiosFetcher<void>(
      {url: `/api/devolucao-mobile/finalizar-demanda/${demandaId}`, method: 'POST', signal
    },
      options);
    }
  


export const getFinalizarDemandaDevolucaoMobileMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof finalizarDemandaDevolucaoMobile>>, TError,{demandaId: string}, TContext>, request?: SecondParameter<typeof axiosFetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof finalizarDemandaDevolucaoMobile>>, TError,{demandaId: string}, TContext> => {

const mutationKey = ['finalizarDemandaDevolucaoMobile'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof finalizarDemandaDevolucaoMobile>>, {demandaId: string}> = (props) => {
          const {demandaId} = props ?? {};

          return  finalizarDemandaDevolucaoMobile(demandaId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type FinalizarDemandaDevolucaoMobileMutationResult = NonNullable<Awaited<ReturnType<typeof finalizarDemandaDevolucaoMobile>>>
    
    export type FinalizarDemandaDevolucaoMobileMutationError = ErrorType<unknown>

    /**
 * @summary Finalizar demanda
 */
export const useFinalizarDemandaDevolucaoMobile = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof finalizarDemandaDevolucaoMobile>>, TError,{demandaId: string}, TContext>, request?: SecondParameter<typeof axiosFetcher>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof finalizarDemandaDevolucaoMobile>>,
        TError,
        {demandaId: string},
        TContext
      > => {

      const mutationOptions = getFinalizarDemandaDevolucaoMobileMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Listar itens contabilizados
 */
export const getItensContabilDevolucaoMobile = (
    demandaId: string,
 options?: SecondParameter<typeof axiosFetcher>,signal?: AbortSignal
) => {
      
      
      return axiosFetcher<ItensContabilDto[]>(
      {url: `/api/devolucao-mobile/get-itens-contabil/${demandaId}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetItensContabilDevolucaoMobileQueryKey = (demandaId?: string,) => {
    return [
    `/api/devolucao-mobile/get-itens-contabil/${demandaId}`
    ] as const;
    }

    
export const getGetItensContabilDevolucaoMobileQueryOptions = <TData = Awaited<ReturnType<typeof getItensContabilDevolucaoMobile>>, TError = ErrorType<unknown>>(demandaId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItensContabilDevolucaoMobile>>, TError, TData>>, request?: SecondParameter<typeof axiosFetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetItensContabilDevolucaoMobileQueryKey(demandaId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getItensContabilDevolucaoMobile>>> = ({ signal }) => getItensContabilDevolucaoMobile(demandaId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(demandaId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getItensContabilDevolucaoMobile>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetItensContabilDevolucaoMobileQueryResult = NonNullable<Awaited<ReturnType<typeof getItensContabilDevolucaoMobile>>>
export type GetItensContabilDevolucaoMobileQueryError = ErrorType<unknown>


export function useGetItensContabilDevolucaoMobile<TData = Awaited<ReturnType<typeof getItensContabilDevolucaoMobile>>, TError = ErrorType<unknown>>(
 demandaId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItensContabilDevolucaoMobile>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getItensContabilDevolucaoMobile>>,
          TError,
          Awaited<ReturnType<typeof getItensContabilDevolucaoMobile>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosFetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetItensContabilDevolucaoMobile<TData = Awaited<ReturnType<typeof getItensContabilDevolucaoMobile>>, TError = ErrorType<unknown>>(
 demandaId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItensContabilDevolucaoMobile>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getItensContabilDevolucaoMobile>>,
          TError,
          Awaited<ReturnType<typeof getItensContabilDevolucaoMobile>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetItensContabilDevolucaoMobile<TData = Awaited<ReturnType<typeof getItensContabilDevolucaoMobile>>, TError = ErrorType<unknown>>(
 demandaId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItensContabilDevolucaoMobile>>, TError, TData>>, request?: SecondParameter<typeof axiosFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Listar itens contabilizados
 */

export function useGetItensContabilDevolucaoMobile<TData = Awaited<ReturnType<typeof getItensContabilDevolucaoMobile>>, TError = ErrorType<unknown>>(
 demandaId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItensContabilDevolucaoMobile>>, TError, TData>>, request?: SecondParameter<typeof axiosFetcher>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetItensContabilDevolucaoMobileQueryOptions(demandaId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Pegar Status pelo ID
 */
export const getStatusById = (
    demandaId: string,
 options?: SecondParameter<typeof axiosFetcher>,signal?: AbortSignal
) => {
      
      
      return axiosFetcher<string>(
      {url: `/api/devolucao-mobile/get-status-by-id/${demandaId}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetStatusByIdQueryKey = (demandaId?: string,) => {
    return [
    `/api/devolucao-mobile/get-status-by-id/${demandaId}`
    ] as const;
    }

    
export const getGetStatusByIdQueryOptions = <TData = Awaited<ReturnType<typeof getStatusById>>, TError = ErrorType<unknown>>(demandaId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStatusById>>, TError, TData>>, request?: SecondParameter<typeof axiosFetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStatusByIdQueryKey(demandaId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStatusById>>> = ({ signal }) => getStatusById(demandaId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(demandaId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getStatusById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetStatusByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getStatusById>>>
export type GetStatusByIdQueryError = ErrorType<unknown>


export function useGetStatusById<TData = Awaited<ReturnType<typeof getStatusById>>, TError = ErrorType<unknown>>(
 demandaId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStatusById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStatusById>>,
          TError,
          Awaited<ReturnType<typeof getStatusById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosFetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStatusById<TData = Awaited<ReturnType<typeof getStatusById>>, TError = ErrorType<unknown>>(
 demandaId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStatusById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStatusById>>,
          TError,
          Awaited<ReturnType<typeof getStatusById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStatusById<TData = Awaited<ReturnType<typeof getStatusById>>, TError = ErrorType<unknown>>(
 demandaId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStatusById>>, TError, TData>>, request?: SecondParameter<typeof axiosFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Pegar Status pelo ID
 */

export function useGetStatusById<TData = Awaited<ReturnType<typeof getStatusById>>, TError = ErrorType<unknown>>(
 demandaId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStatusById>>, TError, TData>>, request?: SecondParameter<typeof axiosFetcher>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetStatusByIdQueryOptions(demandaId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Adicionar anomalia de devolução
 */
export const addAnomaliaDevolucao = (
    anomaliaDevolucaoDto: BodyType<AnomaliaDevolucaoDto>,
 options?: SecondParameter<typeof axiosFetcher>,signal?: AbortSignal
) => {
      
      const formData = new FormData();
formData.append(`demandaId`, anomaliaDevolucaoDto.demandaId.toString())
formData.append(`sku`, anomaliaDevolucaoDto.sku)
formData.append(`descricao`, anomaliaDevolucaoDto.descricao)
formData.append(`lote`, anomaliaDevolucaoDto.lote)
formData.append(`tipo`, anomaliaDevolucaoDto.tipo)
formData.append(`natureza`, anomaliaDevolucaoDto.natureza)
formData.append(`causa`, anomaliaDevolucaoDto.causa)
if(anomaliaDevolucaoDto.tratado !== undefined) {
 formData.append(`tratado`, anomaliaDevolucaoDto.tratado.toString())
 }
formData.append(`quantidadeCaixas`, anomaliaDevolucaoDto.quantidadeCaixas.toString())
formData.append(`quantidadeUnidades`, anomaliaDevolucaoDto.quantidadeUnidades.toString())
anomaliaDevolucaoDto.imagens.forEach(value => formData.append(`imagens`, value));

      return axiosFetcher<void>(
      {url: `/api/devolucao-mobile/add-anomalia-devolucao`, method: 'POST',
      headers: {'Content-Type': 'multipart/form-data', },
       data: formData, signal
    },
      options);
    }
  


export const getAddAnomaliaDevolucaoMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addAnomaliaDevolucao>>, TError,{data: BodyType<AnomaliaDevolucaoDto>}, TContext>, request?: SecondParameter<typeof axiosFetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof addAnomaliaDevolucao>>, TError,{data: BodyType<AnomaliaDevolucaoDto>}, TContext> => {

const mutationKey = ['addAnomaliaDevolucao'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addAnomaliaDevolucao>>, {data: BodyType<AnomaliaDevolucaoDto>}> = (props) => {
          const {data} = props ?? {};

          return  addAnomaliaDevolucao(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AddAnomaliaDevolucaoMutationResult = NonNullable<Awaited<ReturnType<typeof addAnomaliaDevolucao>>>
    export type AddAnomaliaDevolucaoMutationBody = BodyType<AnomaliaDevolucaoDto>
    export type AddAnomaliaDevolucaoMutationError = ErrorType<unknown>

    /**
 * @summary Adicionar anomalia de devolução
 */
export const useAddAnomaliaDevolucao = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addAnomaliaDevolucao>>, TError,{data: BodyType<AnomaliaDevolucaoDto>}, TContext>, request?: SecondParameter<typeof axiosFetcher>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof addAnomaliaDevolucao>>,
        TError,
        {data: BodyType<AnomaliaDevolucaoDto>},
        TContext
      > => {

      const mutationOptions = getAddAnomaliaDevolucaoMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    