/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */
import * as zod from 'zod';


/**
 * @summary Get info me
 */
export const infoMeResponse = zod.object({
  "id": zod.string(),
  "name": zod.string(),
  "empresa": zod.enum(['LDB', 'ITB', 'DPA']),
  "roles": zod.array(zod.string())
})

