/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AddAnomaliaDto,
  AddCheckListDto,
  AddConferenciaCegaDto,
  AddNotaDto,
  DemandDto,
  ItensContabilDto,
  ResponseRavexDto,
  ResultadoDemandaDto
} from '../../model';

import { axiosFetcher } from '../../../http/axios.http';
import type { ErrorType , BodyType } from '../../../http/axios.http';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Buscar resultado de demanda de devolução
 */
export const getResultadoDemandaDevolucao = (
    id: string,
 options?: SecondParameter<typeof axiosFetcher>,signal?: AbortSignal
) => {
      
      
      return axiosFetcher<ResultadoDemandaDto>(
      {url: `/api/devolucao/get-resultado-demanda/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetResultadoDemandaDevolucaoQueryKey = (id?: string,) => {
    return [
    `/api/devolucao/get-resultado-demanda/${id}`
    ] as const;
    }

    
export const getGetResultadoDemandaDevolucaoQueryOptions = <TData = Awaited<ReturnType<typeof getResultadoDemandaDevolucao>>, TError = ErrorType<void>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getResultadoDemandaDevolucao>>, TError, TData>>, request?: SecondParameter<typeof axiosFetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetResultadoDemandaDevolucaoQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getResultadoDemandaDevolucao>>> = ({ signal }) => getResultadoDemandaDevolucao(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getResultadoDemandaDevolucao>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetResultadoDemandaDevolucaoQueryResult = NonNullable<Awaited<ReturnType<typeof getResultadoDemandaDevolucao>>>
export type GetResultadoDemandaDevolucaoQueryError = ErrorType<void>


export function useGetResultadoDemandaDevolucao<TData = Awaited<ReturnType<typeof getResultadoDemandaDevolucao>>, TError = ErrorType<void>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getResultadoDemandaDevolucao>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getResultadoDemandaDevolucao>>,
          TError,
          Awaited<ReturnType<typeof getResultadoDemandaDevolucao>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosFetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetResultadoDemandaDevolucao<TData = Awaited<ReturnType<typeof getResultadoDemandaDevolucao>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getResultadoDemandaDevolucao>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getResultadoDemandaDevolucao>>,
          TError,
          Awaited<ReturnType<typeof getResultadoDemandaDevolucao>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetResultadoDemandaDevolucao<TData = Awaited<ReturnType<typeof getResultadoDemandaDevolucao>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getResultadoDemandaDevolucao>>, TError, TData>>, request?: SecondParameter<typeof axiosFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Buscar resultado de demanda de devolução
 */

export function useGetResultadoDemandaDevolucao<TData = Awaited<ReturnType<typeof getResultadoDemandaDevolucao>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getResultadoDemandaDevolucao>>, TError, TData>>, request?: SecondParameter<typeof axiosFetcher>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetResultadoDemandaDevolucaoQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Busca informações completas de uma viagem pelo ID, incluindo dados do motorista, veículo, transportadora, notas fiscais e itens associados com produtos mapeados.
 * @summary Buscar informações da viagem
 */
export const getInfoByViagemId = (
    viagemId: string,
 options?: SecondParameter<typeof axiosFetcher>,signal?: AbortSignal
) => {
      
      
      return axiosFetcher<ResponseRavexDto>(
      {url: `/api/devolucao/info-by-viagem-id/${viagemId}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetInfoByViagemIdQueryKey = (viagemId?: string,) => {
    return [
    `/api/devolucao/info-by-viagem-id/${viagemId}`
    ] as const;
    }

    
export const getGetInfoByViagemIdQueryOptions = <TData = Awaited<ReturnType<typeof getInfoByViagemId>>, TError = ErrorType<void | void>>(viagemId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInfoByViagemId>>, TError, TData>>, request?: SecondParameter<typeof axiosFetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetInfoByViagemIdQueryKey(viagemId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getInfoByViagemId>>> = ({ signal }) => getInfoByViagemId(viagemId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(viagemId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getInfoByViagemId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetInfoByViagemIdQueryResult = NonNullable<Awaited<ReturnType<typeof getInfoByViagemId>>>
export type GetInfoByViagemIdQueryError = ErrorType<void | void>


export function useGetInfoByViagemId<TData = Awaited<ReturnType<typeof getInfoByViagemId>>, TError = ErrorType<void | void>>(
 viagemId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInfoByViagemId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getInfoByViagemId>>,
          TError,
          Awaited<ReturnType<typeof getInfoByViagemId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosFetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetInfoByViagemId<TData = Awaited<ReturnType<typeof getInfoByViagemId>>, TError = ErrorType<void | void>>(
 viagemId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInfoByViagemId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getInfoByViagemId>>,
          TError,
          Awaited<ReturnType<typeof getInfoByViagemId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetInfoByViagemId<TData = Awaited<ReturnType<typeof getInfoByViagemId>>, TError = ErrorType<void | void>>(
 viagemId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInfoByViagemId>>, TError, TData>>, request?: SecondParameter<typeof axiosFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Buscar informações da viagem
 */

export function useGetInfoByViagemId<TData = Awaited<ReturnType<typeof getInfoByViagemId>>, TError = ErrorType<void | void>>(
 viagemId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInfoByViagemId>>, TError, TData>>, request?: SecondParameter<typeof axiosFetcher>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetInfoByViagemIdQueryOptions(viagemId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Adicionar demanda
 */
export const addDemandaDevolucao = (
    centerId: string,
    demandDto: BodyType<DemandDto>,
 options?: SecondParameter<typeof axiosFetcher>,signal?: AbortSignal
) => {
      
      
      return axiosFetcher<string>(
      {url: `/api/devolucao/add-demanda/${centerId}`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: demandDto, signal
    },
      options);
    }
  


export const getAddDemandaDevolucaoMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addDemandaDevolucao>>, TError,{centerId: string;data: BodyType<DemandDto>}, TContext>, request?: SecondParameter<typeof axiosFetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof addDemandaDevolucao>>, TError,{centerId: string;data: BodyType<DemandDto>}, TContext> => {

const mutationKey = ['addDemandaDevolucao'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addDemandaDevolucao>>, {centerId: string;data: BodyType<DemandDto>}> = (props) => {
          const {centerId,data} = props ?? {};

          return  addDemandaDevolucao(centerId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AddDemandaDevolucaoMutationResult = NonNullable<Awaited<ReturnType<typeof addDemandaDevolucao>>>
    export type AddDemandaDevolucaoMutationBody = BodyType<DemandDto>
    export type AddDemandaDevolucaoMutationError = ErrorType<void>

    /**
 * @summary Adicionar demanda
 */
export const useAddDemandaDevolucao = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addDemandaDevolucao>>, TError,{centerId: string;data: BodyType<DemandDto>}, TContext>, request?: SecondParameter<typeof axiosFetcher>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof addDemandaDevolucao>>,
        TError,
        {centerId: string;data: BodyType<DemandDto>},
        TContext
      > => {

      const mutationOptions = getAddDemandaDevolucaoMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Listar demandas de devolução
 */
export const listarDemandasDevolucao = (
    centerId: string,
    data: string,
 options?: SecondParameter<typeof axiosFetcher>,signal?: AbortSignal
) => {
      
      
      return axiosFetcher<DemandDto[]>(
      {url: `/api/devolucao/listar-demandas/${centerId}/${data}`, method: 'GET', signal
    },
      options);
    }
  



export const getListarDemandasDevolucaoQueryKey = (centerId?: string,
    data?: string,) => {
    return [
    `/api/devolucao/listar-demandas/${centerId}/${data}`
    ] as const;
    }

    
export const getListarDemandasDevolucaoQueryOptions = <TData = Awaited<ReturnType<typeof listarDemandasDevolucao>>, TError = ErrorType<void>>(centerId: string,
    data: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listarDemandasDevolucao>>, TError, TData>>, request?: SecondParameter<typeof axiosFetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListarDemandasDevolucaoQueryKey(centerId,data);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listarDemandasDevolucao>>> = ({ signal }) => listarDemandasDevolucao(centerId,data, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(centerId && data), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listarDemandasDevolucao>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListarDemandasDevolucaoQueryResult = NonNullable<Awaited<ReturnType<typeof listarDemandasDevolucao>>>
export type ListarDemandasDevolucaoQueryError = ErrorType<void>


export function useListarDemandasDevolucao<TData = Awaited<ReturnType<typeof listarDemandasDevolucao>>, TError = ErrorType<void>>(
 centerId: string,
    data: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listarDemandasDevolucao>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listarDemandasDevolucao>>,
          TError,
          Awaited<ReturnType<typeof listarDemandasDevolucao>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosFetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListarDemandasDevolucao<TData = Awaited<ReturnType<typeof listarDemandasDevolucao>>, TError = ErrorType<void>>(
 centerId: string,
    data: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listarDemandasDevolucao>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listarDemandasDevolucao>>,
          TError,
          Awaited<ReturnType<typeof listarDemandasDevolucao>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListarDemandasDevolucao<TData = Awaited<ReturnType<typeof listarDemandasDevolucao>>, TError = ErrorType<void>>(
 centerId: string,
    data: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listarDemandasDevolucao>>, TError, TData>>, request?: SecondParameter<typeof axiosFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Listar demandas de devolução
 */

export function useListarDemandasDevolucao<TData = Awaited<ReturnType<typeof listarDemandasDevolucao>>, TError = ErrorType<void>>(
 centerId: string,
    data: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listarDemandasDevolucao>>, TError, TData>>, request?: SecondParameter<typeof axiosFetcher>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListarDemandasDevolucaoQueryOptions(centerId,data,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Buscar demanda de devolução por ID
 */
export const getDemandaByIdDevolucao = (
    id: string,
 options?: SecondParameter<typeof axiosFetcher>,signal?: AbortSignal
) => {
      
      
      return axiosFetcher<DemandDto>(
      {url: `/api/devolucao/get-demanda-by-id/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetDemandaByIdDevolucaoQueryKey = (id?: string,) => {
    return [
    `/api/devolucao/get-demanda-by-id/${id}`
    ] as const;
    }

    
export const getGetDemandaByIdDevolucaoQueryOptions = <TData = Awaited<ReturnType<typeof getDemandaByIdDevolucao>>, TError = ErrorType<void>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDemandaByIdDevolucao>>, TError, TData>>, request?: SecondParameter<typeof axiosFetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDemandaByIdDevolucaoQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDemandaByIdDevolucao>>> = ({ signal }) => getDemandaByIdDevolucao(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDemandaByIdDevolucao>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDemandaByIdDevolucaoQueryResult = NonNullable<Awaited<ReturnType<typeof getDemandaByIdDevolucao>>>
export type GetDemandaByIdDevolucaoQueryError = ErrorType<void>


export function useGetDemandaByIdDevolucao<TData = Awaited<ReturnType<typeof getDemandaByIdDevolucao>>, TError = ErrorType<void>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDemandaByIdDevolucao>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDemandaByIdDevolucao>>,
          TError,
          Awaited<ReturnType<typeof getDemandaByIdDevolucao>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosFetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDemandaByIdDevolucao<TData = Awaited<ReturnType<typeof getDemandaByIdDevolucao>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDemandaByIdDevolucao>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDemandaByIdDevolucao>>,
          TError,
          Awaited<ReturnType<typeof getDemandaByIdDevolucao>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDemandaByIdDevolucao<TData = Awaited<ReturnType<typeof getDemandaByIdDevolucao>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDemandaByIdDevolucao>>, TError, TData>>, request?: SecondParameter<typeof axiosFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Buscar demanda de devolução por ID
 */

export function useGetDemandaByIdDevolucao<TData = Awaited<ReturnType<typeof getDemandaByIdDevolucao>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDemandaByIdDevolucao>>, TError, TData>>, request?: SecondParameter<typeof axiosFetcher>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetDemandaByIdDevolucaoQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Adicionar nota de devolução
 */
export const addNotaDevolucao = (
    addNotaDto: BodyType<AddNotaDto>,
 options?: SecondParameter<typeof axiosFetcher>,signal?: AbortSignal
) => {
      
      
      return axiosFetcher<string>(
      {url: `/api/devolucao/add-nota`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addNotaDto, signal
    },
      options);
    }
  


export const getAddNotaDevolucaoMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addNotaDevolucao>>, TError,{data: BodyType<AddNotaDto>}, TContext>, request?: SecondParameter<typeof axiosFetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof addNotaDevolucao>>, TError,{data: BodyType<AddNotaDto>}, TContext> => {

const mutationKey = ['addNotaDevolucao'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addNotaDevolucao>>, {data: BodyType<AddNotaDto>}> = (props) => {
          const {data} = props ?? {};

          return  addNotaDevolucao(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AddNotaDevolucaoMutationResult = NonNullable<Awaited<ReturnType<typeof addNotaDevolucao>>>
    export type AddNotaDevolucaoMutationBody = BodyType<AddNotaDto>
    export type AddNotaDevolucaoMutationError = ErrorType<void>

    /**
 * @summary Adicionar nota de devolução
 */
export const useAddNotaDevolucao = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addNotaDevolucao>>, TError,{data: BodyType<AddNotaDto>}, TContext>, request?: SecondParameter<typeof axiosFetcher>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof addNotaDevolucao>>,
        TError,
        {data: BodyType<AddNotaDto>},
        TContext
      > => {

      const mutationOptions = getAddNotaDevolucaoMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Liberar demanda para conferência
 */
export const liberarDemandaDevolucao = (
    demandaId: string,
 options?: SecondParameter<typeof axiosFetcher>,signal?: AbortSignal
) => {
      
      
      return axiosFetcher<string>(
      {url: `/api/devolucao/liberar-demanda/${demandaId}`, method: 'POST', signal
    },
      options);
    }
  


export const getLiberarDemandaDevolucaoMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof liberarDemandaDevolucao>>, TError,{demandaId: string}, TContext>, request?: SecondParameter<typeof axiosFetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof liberarDemandaDevolucao>>, TError,{demandaId: string}, TContext> => {

const mutationKey = ['liberarDemandaDevolucao'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof liberarDemandaDevolucao>>, {demandaId: string}> = (props) => {
          const {demandaId} = props ?? {};

          return  liberarDemandaDevolucao(demandaId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LiberarDemandaDevolucaoMutationResult = NonNullable<Awaited<ReturnType<typeof liberarDemandaDevolucao>>>
    
    export type LiberarDemandaDevolucaoMutationError = ErrorType<void>

    /**
 * @summary Liberar demanda para conferência
 */
export const useLiberarDemandaDevolucao = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof liberarDemandaDevolucao>>, TError,{demandaId: string}, TContext>, request?: SecondParameter<typeof axiosFetcher>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof liberarDemandaDevolucao>>,
        TError,
        {demandaId: string},
        TContext
      > => {

      const mutationOptions = getLiberarDemandaDevolucaoMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Listar demandas em aberto
 */
export const listarDemandasEmAbertoDevolucaoMobile = (
    centerId: string,
 options?: SecondParameter<typeof axiosFetcher>,signal?: AbortSignal
) => {
      
      
      return axiosFetcher<DemandDto[]>(
      {url: `/api/devolucao/listar-demandas-em-aberto/${centerId}`, method: 'GET', signal
    },
      options);
    }
  



export const getListarDemandasEmAbertoDevolucaoMobileQueryKey = (centerId?: string,) => {
    return [
    `/api/devolucao/listar-demandas-em-aberto/${centerId}`
    ] as const;
    }

    
export const getListarDemandasEmAbertoDevolucaoMobileQueryOptions = <TData = Awaited<ReturnType<typeof listarDemandasEmAbertoDevolucaoMobile>>, TError = ErrorType<void>>(centerId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listarDemandasEmAbertoDevolucaoMobile>>, TError, TData>>, request?: SecondParameter<typeof axiosFetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListarDemandasEmAbertoDevolucaoMobileQueryKey(centerId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listarDemandasEmAbertoDevolucaoMobile>>> = ({ signal }) => listarDemandasEmAbertoDevolucaoMobile(centerId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(centerId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listarDemandasEmAbertoDevolucaoMobile>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListarDemandasEmAbertoDevolucaoMobileQueryResult = NonNullable<Awaited<ReturnType<typeof listarDemandasEmAbertoDevolucaoMobile>>>
export type ListarDemandasEmAbertoDevolucaoMobileQueryError = ErrorType<void>


export function useListarDemandasEmAbertoDevolucaoMobile<TData = Awaited<ReturnType<typeof listarDemandasEmAbertoDevolucaoMobile>>, TError = ErrorType<void>>(
 centerId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listarDemandasEmAbertoDevolucaoMobile>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listarDemandasEmAbertoDevolucaoMobile>>,
          TError,
          Awaited<ReturnType<typeof listarDemandasEmAbertoDevolucaoMobile>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosFetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListarDemandasEmAbertoDevolucaoMobile<TData = Awaited<ReturnType<typeof listarDemandasEmAbertoDevolucaoMobile>>, TError = ErrorType<void>>(
 centerId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listarDemandasEmAbertoDevolucaoMobile>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listarDemandasEmAbertoDevolucaoMobile>>,
          TError,
          Awaited<ReturnType<typeof listarDemandasEmAbertoDevolucaoMobile>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListarDemandasEmAbertoDevolucaoMobile<TData = Awaited<ReturnType<typeof listarDemandasEmAbertoDevolucaoMobile>>, TError = ErrorType<void>>(
 centerId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listarDemandasEmAbertoDevolucaoMobile>>, TError, TData>>, request?: SecondParameter<typeof axiosFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Listar demandas em aberto
 */

export function useListarDemandasEmAbertoDevolucaoMobile<TData = Awaited<ReturnType<typeof listarDemandasEmAbertoDevolucaoMobile>>, TError = ErrorType<void>>(
 centerId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listarDemandasEmAbertoDevolucaoMobile>>, TError, TData>>, request?: SecondParameter<typeof axiosFetcher>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListarDemandasEmAbertoDevolucaoMobileQueryOptions(centerId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Iniciar conferência
 */
export const startDemandaDevolucaoMobile = (
    demandaId: string,
    doca: string,
 options?: SecondParameter<typeof axiosFetcher>,signal?: AbortSignal
) => {
      
      
      return axiosFetcher<string>(
      {url: `/api/devolucao/start-demanda/${demandaId}/${doca}`, method: 'POST', signal
    },
      options);
    }
  


export const getStartDemandaDevolucaoMobileMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof startDemandaDevolucaoMobile>>, TError,{demandaId: string;doca: string}, TContext>, request?: SecondParameter<typeof axiosFetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof startDemandaDevolucaoMobile>>, TError,{demandaId: string;doca: string}, TContext> => {

const mutationKey = ['startDemandaDevolucaoMobile'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof startDemandaDevolucaoMobile>>, {demandaId: string;doca: string}> = (props) => {
          const {demandaId,doca} = props ?? {};

          return  startDemandaDevolucaoMobile(demandaId,doca,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type StartDemandaDevolucaoMobileMutationResult = NonNullable<Awaited<ReturnType<typeof startDemandaDevolucaoMobile>>>
    
    export type StartDemandaDevolucaoMobileMutationError = ErrorType<void>

    /**
 * @summary Iniciar conferência
 */
export const useStartDemandaDevolucaoMobile = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof startDemandaDevolucaoMobile>>, TError,{demandaId: string;doca: string}, TContext>, request?: SecondParameter<typeof axiosFetcher>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof startDemandaDevolucaoMobile>>,
        TError,
        {demandaId: string;doca: string},
        TContext
      > => {

      const mutationOptions = getStartDemandaDevolucaoMobileMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Listar itens contabilizados
 */
export const getItensContabilDevolucaoMobile = (
    demandaId: string,
 options?: SecondParameter<typeof axiosFetcher>,signal?: AbortSignal
) => {
      
      
      return axiosFetcher<ItensContabilDto[]>(
      {url: `/api/devolucao/get-itens-contabil/${demandaId}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetItensContabilDevolucaoMobileQueryKey = (demandaId?: string,) => {
    return [
    `/api/devolucao/get-itens-contabil/${demandaId}`
    ] as const;
    }

    
export const getGetItensContabilDevolucaoMobileQueryOptions = <TData = Awaited<ReturnType<typeof getItensContabilDevolucaoMobile>>, TError = ErrorType<void>>(demandaId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItensContabilDevolucaoMobile>>, TError, TData>>, request?: SecondParameter<typeof axiosFetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetItensContabilDevolucaoMobileQueryKey(demandaId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getItensContabilDevolucaoMobile>>> = ({ signal }) => getItensContabilDevolucaoMobile(demandaId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(demandaId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getItensContabilDevolucaoMobile>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetItensContabilDevolucaoMobileQueryResult = NonNullable<Awaited<ReturnType<typeof getItensContabilDevolucaoMobile>>>
export type GetItensContabilDevolucaoMobileQueryError = ErrorType<void>


export function useGetItensContabilDevolucaoMobile<TData = Awaited<ReturnType<typeof getItensContabilDevolucaoMobile>>, TError = ErrorType<void>>(
 demandaId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItensContabilDevolucaoMobile>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getItensContabilDevolucaoMobile>>,
          TError,
          Awaited<ReturnType<typeof getItensContabilDevolucaoMobile>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosFetcher>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetItensContabilDevolucaoMobile<TData = Awaited<ReturnType<typeof getItensContabilDevolucaoMobile>>, TError = ErrorType<void>>(
 demandaId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItensContabilDevolucaoMobile>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getItensContabilDevolucaoMobile>>,
          TError,
          Awaited<ReturnType<typeof getItensContabilDevolucaoMobile>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetItensContabilDevolucaoMobile<TData = Awaited<ReturnType<typeof getItensContabilDevolucaoMobile>>, TError = ErrorType<void>>(
 demandaId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItensContabilDevolucaoMobile>>, TError, TData>>, request?: SecondParameter<typeof axiosFetcher>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Listar itens contabilizados
 */

export function useGetItensContabilDevolucaoMobile<TData = Awaited<ReturnType<typeof getItensContabilDevolucaoMobile>>, TError = ErrorType<void>>(
 demandaId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItensContabilDevolucaoMobile>>, TError, TData>>, request?: SecondParameter<typeof axiosFetcher>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetItensContabilDevolucaoMobileQueryOptions(demandaId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Adicionar check list
 */
export const addCheckListDevolucaoMobile = (
    demandaId: string,
    addCheckListDto: BodyType<AddCheckListDto>,
 options?: SecondParameter<typeof axiosFetcher>,signal?: AbortSignal
) => {
      
      
      return axiosFetcher<void>(
      {url: `/api/devolucao/add-check-list/${demandaId}`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addCheckListDto, signal
    },
      options);
    }
  


export const getAddCheckListDevolucaoMobileMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addCheckListDevolucaoMobile>>, TError,{demandaId: string;data: BodyType<AddCheckListDto>}, TContext>, request?: SecondParameter<typeof axiosFetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof addCheckListDevolucaoMobile>>, TError,{demandaId: string;data: BodyType<AddCheckListDto>}, TContext> => {

const mutationKey = ['addCheckListDevolucaoMobile'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addCheckListDevolucaoMobile>>, {demandaId: string;data: BodyType<AddCheckListDto>}> = (props) => {
          const {demandaId,data} = props ?? {};

          return  addCheckListDevolucaoMobile(demandaId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AddCheckListDevolucaoMobileMutationResult = NonNullable<Awaited<ReturnType<typeof addCheckListDevolucaoMobile>>>
    export type AddCheckListDevolucaoMobileMutationBody = BodyType<AddCheckListDto>
    export type AddCheckListDevolucaoMobileMutationError = ErrorType<void>

    /**
 * @summary Adicionar check list
 */
export const useAddCheckListDevolucaoMobile = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addCheckListDevolucaoMobile>>, TError,{demandaId: string;data: BodyType<AddCheckListDto>}, TContext>, request?: SecondParameter<typeof axiosFetcher>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof addCheckListDevolucaoMobile>>,
        TError,
        {demandaId: string;data: BodyType<AddCheckListDto>},
        TContext
      > => {

      const mutationOptions = getAddCheckListDevolucaoMobileMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Iniciar conferência
 */
export const addContagemCega = (
    demandaId: string,
    addConferenciaCegaDto: BodyType<AddConferenciaCegaDto[]>,
 options?: SecondParameter<typeof axiosFetcher>,signal?: AbortSignal
) => {
      
      
      return axiosFetcher<void>(
      {url: `/api/devolucao/add-contagem-cega/${demandaId}`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addConferenciaCegaDto, signal
    },
      options);
    }
  


export const getAddContagemCegaMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addContagemCega>>, TError,{demandaId: string;data: BodyType<AddConferenciaCegaDto[]>}, TContext>, request?: SecondParameter<typeof axiosFetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof addContagemCega>>, TError,{demandaId: string;data: BodyType<AddConferenciaCegaDto[]>}, TContext> => {

const mutationKey = ['addContagemCega'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addContagemCega>>, {demandaId: string;data: BodyType<AddConferenciaCegaDto[]>}> = (props) => {
          const {demandaId,data} = props ?? {};

          return  addContagemCega(demandaId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AddContagemCegaMutationResult = NonNullable<Awaited<ReturnType<typeof addContagemCega>>>
    export type AddContagemCegaMutationBody = BodyType<AddConferenciaCegaDto[]>
    export type AddContagemCegaMutationError = ErrorType<void>

    /**
 * @summary Iniciar conferência
 */
export const useAddContagemCega = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addContagemCega>>, TError,{demandaId: string;data: BodyType<AddConferenciaCegaDto[]>}, TContext>, request?: SecondParameter<typeof axiosFetcher>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof addContagemCega>>,
        TError,
        {demandaId: string;data: BodyType<AddConferenciaCegaDto[]>},
        TContext
      > => {

      const mutationOptions = getAddContagemCegaMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Finalizar demanda
 */
export const finalizarDemandaDevolucaoMobile = (
    demandaId: string,
 options?: SecondParameter<typeof axiosFetcher>,signal?: AbortSignal
) => {
      
      
      return axiosFetcher<void>(
      {url: `/api/devolucao/finalizar-demanda/${demandaId}`, method: 'POST', signal
    },
      options);
    }
  


export const getFinalizarDemandaDevolucaoMobileMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof finalizarDemandaDevolucaoMobile>>, TError,{demandaId: string}, TContext>, request?: SecondParameter<typeof axiosFetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof finalizarDemandaDevolucaoMobile>>, TError,{demandaId: string}, TContext> => {

const mutationKey = ['finalizarDemandaDevolucaoMobile'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof finalizarDemandaDevolucaoMobile>>, {demandaId: string}> = (props) => {
          const {demandaId} = props ?? {};

          return  finalizarDemandaDevolucaoMobile(demandaId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type FinalizarDemandaDevolucaoMobileMutationResult = NonNullable<Awaited<ReturnType<typeof finalizarDemandaDevolucaoMobile>>>
    
    export type FinalizarDemandaDevolucaoMobileMutationError = ErrorType<void>

    /**
 * @summary Finalizar demanda
 */
export const useFinalizarDemandaDevolucaoMobile = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof finalizarDemandaDevolucaoMobile>>, TError,{demandaId: string}, TContext>, request?: SecondParameter<typeof axiosFetcher>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof finalizarDemandaDevolucaoMobile>>,
        TError,
        {demandaId: string},
        TContext
      > => {

      const mutationOptions = getFinalizarDemandaDevolucaoMobileMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Adicionar anomalia de devolução
 */
export const addAnomaliaDevolucao = (
    addAnomaliaDto: BodyType<AddAnomaliaDto>,
 options?: SecondParameter<typeof axiosFetcher>,signal?: AbortSignal
) => {
      
      
      return axiosFetcher<void>(
      {url: `/api/devolucao/add-anomalia-devolucao`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addAnomaliaDto, signal
    },
      options);
    }
  


export const getAddAnomaliaDevolucaoMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addAnomaliaDevolucao>>, TError,{data: BodyType<AddAnomaliaDto>}, TContext>, request?: SecondParameter<typeof axiosFetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof addAnomaliaDevolucao>>, TError,{data: BodyType<AddAnomaliaDto>}, TContext> => {

const mutationKey = ['addAnomaliaDevolucao'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addAnomaliaDevolucao>>, {data: BodyType<AddAnomaliaDto>}> = (props) => {
          const {data} = props ?? {};

          return  addAnomaliaDevolucao(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AddAnomaliaDevolucaoMutationResult = NonNullable<Awaited<ReturnType<typeof addAnomaliaDevolucao>>>
    export type AddAnomaliaDevolucaoMutationBody = BodyType<AddAnomaliaDto>
    export type AddAnomaliaDevolucaoMutationError = ErrorType<void>

    /**
 * @summary Adicionar anomalia de devolução
 */
export const useAddAnomaliaDevolucao = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addAnomaliaDevolucao>>, TError,{data: BodyType<AddAnomaliaDto>}, TContext>, request?: SecondParameter<typeof axiosFetcher>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof addAnomaliaDevolucao>>,
        TError,
        {data: BodyType<AddAnomaliaDto>},
        TContext
      > => {

      const mutationOptions = getAddAnomaliaDevolucaoMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Gerar URL pré-assinada para upload de check list
 */
export const getPresignedUrlCheckListDevolucao = (
    filename: string,
 options?: SecondParameter<typeof axiosFetcher>,signal?: AbortSignal
) => {
      
      
      return axiosFetcher<string>(
      {url: `/api/devolucao/presigned-url-devolucao/check-list/${filename}`, method: 'POST', signal
    },
      options);
    }
  


export const getGetPresignedUrlCheckListDevolucaoMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getPresignedUrlCheckListDevolucao>>, TError,{filename: string}, TContext>, request?: SecondParameter<typeof axiosFetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof getPresignedUrlCheckListDevolucao>>, TError,{filename: string}, TContext> => {

const mutationKey = ['getPresignedUrlCheckListDevolucao'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getPresignedUrlCheckListDevolucao>>, {filename: string}> = (props) => {
          const {filename} = props ?? {};

          return  getPresignedUrlCheckListDevolucao(filename,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type GetPresignedUrlCheckListDevolucaoMutationResult = NonNullable<Awaited<ReturnType<typeof getPresignedUrlCheckListDevolucao>>>
    
    export type GetPresignedUrlCheckListDevolucaoMutationError = ErrorType<void>

    /**
 * @summary Gerar URL pré-assinada para upload de check list
 */
export const useGetPresignedUrlCheckListDevolucao = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getPresignedUrlCheckListDevolucao>>, TError,{filename: string}, TContext>, request?: SecondParameter<typeof axiosFetcher>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getPresignedUrlCheckListDevolucao>>,
        TError,
        {filename: string},
        TContext
      > => {

      const mutationOptions = getGetPresignedUrlCheckListDevolucaoMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Gerar URL pré-assinada para upload de anomalia
 */
export const getPresignedUrlAnomaliaDevolucao = (
    filename: string,
 options?: SecondParameter<typeof axiosFetcher>,signal?: AbortSignal
) => {
      
      
      return axiosFetcher<string>(
      {url: `/api/devolucao/presigned-url-devolucao/anomalia/${filename}`, method: 'POST', signal
    },
      options);
    }
  


export const getGetPresignedUrlAnomaliaDevolucaoMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getPresignedUrlAnomaliaDevolucao>>, TError,{filename: string}, TContext>, request?: SecondParameter<typeof axiosFetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof getPresignedUrlAnomaliaDevolucao>>, TError,{filename: string}, TContext> => {

const mutationKey = ['getPresignedUrlAnomaliaDevolucao'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getPresignedUrlAnomaliaDevolucao>>, {filename: string}> = (props) => {
          const {filename} = props ?? {};

          return  getPresignedUrlAnomaliaDevolucao(filename,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type GetPresignedUrlAnomaliaDevolucaoMutationResult = NonNullable<Awaited<ReturnType<typeof getPresignedUrlAnomaliaDevolucao>>>
    
    export type GetPresignedUrlAnomaliaDevolucaoMutationError = ErrorType<void>

    /**
 * @summary Gerar URL pré-assinada para upload de anomalia
 */
export const useGetPresignedUrlAnomaliaDevolucao = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getPresignedUrlAnomaliaDevolucao>>, TError,{filename: string}, TContext>, request?: SecondParameter<typeof axiosFetcher>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getPresignedUrlAnomaliaDevolucao>>,
        TError,
        {filename: string},
        TContext
      > => {

      const mutationOptions = getGetPresignedUrlAnomaliaDevolucaoMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Gerar URL pré-assinada para upload de fim de devolução
 */
export const getPresignedUrlFimDevolucao = (
    filename: string,
 options?: SecondParameter<typeof axiosFetcher>,signal?: AbortSignal
) => {
      
      
      return axiosFetcher<string>(
      {url: `/api/devolucao/presigned-url-devolucao/fim-devolucao/${filename}`, method: 'POST', signal
    },
      options);
    }
  


export const getGetPresignedUrlFimDevolucaoMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getPresignedUrlFimDevolucao>>, TError,{filename: string}, TContext>, request?: SecondParameter<typeof axiosFetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof getPresignedUrlFimDevolucao>>, TError,{filename: string}, TContext> => {

const mutationKey = ['getPresignedUrlFimDevolucao'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getPresignedUrlFimDevolucao>>, {filename: string}> = (props) => {
          const {filename} = props ?? {};

          return  getPresignedUrlFimDevolucao(filename,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type GetPresignedUrlFimDevolucaoMutationResult = NonNullable<Awaited<ReturnType<typeof getPresignedUrlFimDevolucao>>>
    
    export type GetPresignedUrlFimDevolucaoMutationError = ErrorType<void>

    /**
 * @summary Gerar URL pré-assinada para upload de fim de devolução
 */
export const useGetPresignedUrlFimDevolucao = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getPresignedUrlFimDevolucao>>, TError,{filename: string}, TContext>, request?: SecondParameter<typeof axiosFetcher>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getPresignedUrlFimDevolucao>>,
        TError,
        {filename: string},
        TContext
      > => {

      const mutationOptions = getGetPresignedUrlFimDevolucaoMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Adicionar imagem de fim de devolução
 */
export const addImagemFimDevolucao = (
    demandaId: string,
    addImagemFimDevolucaoBody: BodyType<string[]>,
 options?: SecondParameter<typeof axiosFetcher>,signal?: AbortSignal
) => {
      
      
      return axiosFetcher<void>(
      {url: `/api/devolucao/add-imagem-fim/${demandaId}`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addImagemFimDevolucaoBody, signal
    },
      options);
    }
  


export const getAddImagemFimDevolucaoMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addImagemFimDevolucao>>, TError,{demandaId: string;data: BodyType<string[]>}, TContext>, request?: SecondParameter<typeof axiosFetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof addImagemFimDevolucao>>, TError,{demandaId: string;data: BodyType<string[]>}, TContext> => {

const mutationKey = ['addImagemFimDevolucao'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addImagemFimDevolucao>>, {demandaId: string;data: BodyType<string[]>}> = (props) => {
          const {demandaId,data} = props ?? {};

          return  addImagemFimDevolucao(demandaId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AddImagemFimDevolucaoMutationResult = NonNullable<Awaited<ReturnType<typeof addImagemFimDevolucao>>>
    export type AddImagemFimDevolucaoMutationBody = BodyType<string[]>
    export type AddImagemFimDevolucaoMutationError = ErrorType<void>

    /**
 * @summary Adicionar imagem de fim de devolução
 */
export const useAddImagemFimDevolucao = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addImagemFimDevolucao>>, TError,{demandaId: string;data: BodyType<string[]>}, TContext>, request?: SecondParameter<typeof axiosFetcher>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof addImagemFimDevolucao>>,
        TError,
        {demandaId: string;data: BodyType<string[]>},
        TContext
      > => {

      const mutationOptions = getAddImagemFimDevolucaoMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    