/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */

export interface AddCheckListDto {
  /** @minLength 1 */
  demandaId: string;
  /** @pattern ^-?\d+(\.\d+)?$ */
  temperaturaBau: string;
  /** @pattern ^-?\d+(\.\d+)?$ */
  temperaturaProduto: string;
  anomalias?: string;
}
