/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */

export interface AddCheckListDto {
  /** Foto do baú aberto */
  fotoBauAberto: string;
  /** Foto do baú fechado */
  fotoBauFechado: string;
  demandaId: string;
  /** Temperatura do Baú */
  temperaturaBau: string;
  /** Temperatura do Produto */
  temperaturaProduto: string;
  anomalias?: string;
}
