/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */

export interface AddDemandaDto {
  /** Placa do veiculo */
  placa: string;
  /** Nome Motorista */
  motorista: string;
  /** Nome Transportadora */
  idTransportadora: string;
  /** Id Viagem Ravex */
  viagemId: string;
  /** Telefone Motorista */
  telefone: string;
  /** Existe carga segregada */
  cargaSegregada: boolean;
  /** Quantos paletes estão sendo retornados */
  paletesRetorno: number;
  /** Qual doca o carro vai ser descarregado */
  doca: string;
}
