/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */
import type { AddNotaDtoEmpresa } from './addNotaDtoEmpresa';
import type { AddNotaDtoTipo } from './addNotaDtoTipo';
import type { AddNotaDtoItensItem } from './addNotaDtoItensItem';

export interface AddNotaDto {
  empresa: AddNotaDtoEmpresa;
  devolucaoDemandaId: number;
  notaFiscal: string;
  motivoDevolucao: string;
  descMotivoDevolucao: string;
  nfParcial?: string;
  idViagemRavex?: string;
  tipo: AddNotaDtoTipo;
  itens: AddNotaDtoItensItem[];
}
