/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */

export interface AnomaliaDevolucaoDto {
  /** ID da demanda de devolução */
  demandaId: number;
  /** Código SKU do produto */
  sku: string;
  /** Descrição da anomalia */
  descricao: string;
  /** Lote do produto */
  lote: string;
  /** Tipo da anomalia */
  tipo: string;
  /** Natureza da anomalia */
  natureza: string;
  /** Causa da anomalia */
  causa: string;
  /** Indica se a anomalia já foi tratada */
  tratado?: boolean;
  /** Quantidade de caixas afetadas */
  quantidadeCaixas: number;
  /** Quantidade de unidades afetadas */
  quantidadeUnidades: number;
  /** Lista de URLs ou identificadores das imagens */
  imagens: string[];
}
