/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */

export type BuscarTodosTransportesSemTransporteStatus = typeof BuscarTodosTransportesSemTransporteStatus[keyof typeof BuscarTodosTransportesSemTransporteStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BuscarTodosTransportesSemTransporteStatus = {
  AGUARDANDO_SEPARACAO: 'AGUARDANDO_SEPARACAO',
  EM_SEPARACAO: 'EM_SEPARACAO',
  SEPARACAO_CONCLUIDA: 'SEPARACAO_CONCLUIDA',
  EM_CONFERENCIA: 'EM_CONFERENCIA',
  CONFERENCIA_CONCLUIDA: 'CONFERENCIA_CONCLUIDA',
  EM_CARREGAMENTO: 'EM_CARREGAMENTO',
  CARREGAMENTO_CONCLUIDO: 'CARREGAMENTO_CONCLUIDO',
  FATURADO: 'FATURADO',
  LIBERADO_PORTARIA: 'LIBERADO_PORTARIA',
  CANCELADO: 'CANCELADO',
} as const;
