/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */
import type { BuscarTodosOsCortesDeProdutoMotivo } from './buscarTodosOsCortesDeProdutoMotivo';

export type BuscarTodosOsCortesDeProdutoParams = {
produto?: string;
lote?: string;
motivo?: BuscarTodosOsCortesDeProdutoMotivo;
realizado?: boolean;
criadoPorId?: string;
transporteId?: string;
direcao?: 'OPERACIONAL' | 'ADMINISTRATIVO' | null;
centerId?: string;
descricao?: string | null;
realizadoPorId?: string | null;
inicio?: string;
fim?: string;
};
