/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */
import type { BuscarTodosTransportesStatus } from './buscarTodosTransportesStatus';
import type { BuscarTodosTransportesCarregamento } from './buscarTodosTransportesCarregamento';
import type { BuscarTodosTransportesConferencia } from './buscarTodosTransportesConferencia';
import type { BuscarTodosTransportesSeparacao } from './buscarTodosTransportesSeparacao';

export type BuscarTodosTransportesParams = {
numeroTransporte?: string;
status?: BuscarTodosTransportesStatus;
/**
 * @minLength 1
 */
nomeRota?: string;
/**
 * @minLength 1
 */
nomeTransportadora?: string;
/**
 * @minLength 1
 */
placa?: string;
/**
 * @minLength 1
 */
criadoEm?: string;
/**
 * @minLength 1
 */
atualizadoEm?: string;
/**
 * @minLength 1
 */
cadastradoPorId?: string;
/**
 * @minLength 1
 */
dataExpedicao?: string;
/**
 * @minLength 1
 */
centerId?: string;
obs?: string | null;
prioridade?: number;
cargaParada?: boolean;
carregamento?: BuscarTodosTransportesCarregamento;
conferencia?: BuscarTodosTransportesConferencia;
separacao?: BuscarTodosTransportesSeparacao;
qtdImpressoes?: number;
};
