/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */
import type { BuscarPausasAtivasProcesso } from './buscarPausasAtivasProcesso';
import type { BuscarPausasAtivasTurno } from './buscarPausasAtivasTurno';
import type { BuscarPausasAtivasAtivo } from './buscarPausasAtivasAtivo';

export type BuscarPausasAtivasParams = {
/**
 * @minimum -2147483648
 * @maximum 2147483647
 */
id?: number;
inicio?: string;
fim?: string | null;
motivo?: string;
processo?: BuscarPausasAtivasProcesso;
turno?: BuscarPausasAtivasTurno;
registradoPorId?: string;
criadoEm?: string;
atualizadoEm?: string;
segmento?: string;
ativo?: BuscarPausasAtivasAtivo;
};
