/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */
import type { ConfiguracaoImpressaoMapaDtoOutputTipoImpressao } from './configuracaoImpressaoMapaDtoOutputTipoImpressao';
import type { ConfiguracaoImpressaoMapaDtoOutputTipoQuebra } from './configuracaoImpressaoMapaDtoOutputTipoQuebra';
import type { ConfiguracaoImpressaoMapaDtoOutputValorQuebra } from './configuracaoImpressaoMapaDtoOutputValorQuebra';
import type { ConfiguracaoImpressaoMapaDtoOutputExibirInfoCabecalho } from './configuracaoImpressaoMapaDtoOutputExibirInfoCabecalho';
import type { ConfiguracaoImpressaoMapaDtoOutputSegregarFifo } from './configuracaoImpressaoMapaDtoOutputSegregarFifo';
import type { ConfiguracaoImpressaoMapaDtoOutputAtribuidoPorId } from './configuracaoImpressaoMapaDtoOutputAtribuidoPorId';
import type { ConfiguracaoImpressaoMapaDtoOutputTipoImpressaoConferencia } from './configuracaoImpressaoMapaDtoOutputTipoImpressaoConferencia';
import type { ConfiguracaoImpressaoMapaDtoOutputOrdemConferencia } from './configuracaoImpressaoMapaDtoOutputOrdemConferencia';
import type { ConfiguracaoImpressaoMapaDtoOutputOrdemFifo } from './configuracaoImpressaoMapaDtoOutputOrdemFifo';
import type { ConfiguracaoImpressaoMapaDtoOutputOrdemPaletes } from './configuracaoImpressaoMapaDtoOutputOrdemPaletes';
import type { ConfiguracaoImpressaoMapaDtoOutputOrdemPicking } from './configuracaoImpressaoMapaDtoOutputOrdemPicking';
import type { ConfiguracaoImpressaoMapaDtoOutputOrdemUnidades } from './configuracaoImpressaoMapaDtoOutputOrdemUnidades';

export interface ConfiguracaoImpressaoMapaDtoOutput {
  id: string;
  tipoImpressao: ConfiguracaoImpressaoMapaDtoOutputTipoImpressao;
  quebraPalete: boolean;
  tipoQuebra: ConfiguracaoImpressaoMapaDtoOutputTipoQuebra;
  valorQuebra: ConfiguracaoImpressaoMapaDtoOutputValorQuebra;
  separarPaleteFull: boolean;
  separarUnidades: boolean;
  exibirInfoCabecalho: ConfiguracaoImpressaoMapaDtoOutputExibirInfoCabecalho;
  segregarFifo: ConfiguracaoImpressaoMapaDtoOutputSegregarFifo;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  dataMaximaPercentual: number;
  createdAt: string;
  updatedAt: string;
  centerId: string;
  atribuidoPorId: ConfiguracaoImpressaoMapaDtoOutputAtribuidoPorId;
  empresa: string;
  tipoImpressaoConferencia: ConfiguracaoImpressaoMapaDtoOutputTipoImpressaoConferencia;
  ordemConferencia: ConfiguracaoImpressaoMapaDtoOutputOrdemConferencia;
  ordemFifo: ConfiguracaoImpressaoMapaDtoOutputOrdemFifo;
  ordemPaletes: ConfiguracaoImpressaoMapaDtoOutputOrdemPaletes;
  ordemPicking: ConfiguracaoImpressaoMapaDtoOutputOrdemPicking;
  ordemUnidades: ConfiguracaoImpressaoMapaDtoOutputOrdemUnidades;
}
