/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */
import type { ConfiguracaoImpressaoMapaDtoTipoImpressao } from './configuracaoImpressaoMapaDtoTipoImpressao';
import type { ConfiguracaoImpressaoMapaDtoTipoQuebra } from './configuracaoImpressaoMapaDtoTipoQuebra';
import type { ConfiguracaoImpressaoMapaDtoValorQuebra } from './configuracaoImpressaoMapaDtoValorQuebra';
import type { ConfiguracaoImpressaoMapaDtoExibirInfoCabecalho } from './configuracaoImpressaoMapaDtoExibirInfoCabecalho';
import type { ConfiguracaoImpressaoMapaDtoSegregarFifo } from './configuracaoImpressaoMapaDtoSegregarFifo';
import type { ConfiguracaoImpressaoMapaDtoAtribuidoPorId } from './configuracaoImpressaoMapaDtoAtribuidoPorId';
import type { ConfiguracaoImpressaoMapaDtoTipoImpressaoConferencia } from './configuracaoImpressaoMapaDtoTipoImpressaoConferencia';
import type { ConfiguracaoImpressaoMapaDtoOrdemConferencia } from './configuracaoImpressaoMapaDtoOrdemConferencia';
import type { ConfiguracaoImpressaoMapaDtoOrdemFifo } from './configuracaoImpressaoMapaDtoOrdemFifo';
import type { ConfiguracaoImpressaoMapaDtoOrdemPaletes } from './configuracaoImpressaoMapaDtoOrdemPaletes';
import type { ConfiguracaoImpressaoMapaDtoOrdemPicking } from './configuracaoImpressaoMapaDtoOrdemPicking';
import type { ConfiguracaoImpressaoMapaDtoOrdemUnidades } from './configuracaoImpressaoMapaDtoOrdemUnidades';

export interface ConfiguracaoImpressaoMapaDto {
  id: string;
  tipoImpressao: ConfiguracaoImpressaoMapaDtoTipoImpressao;
  quebraPalete: boolean;
  tipoQuebra: ConfiguracaoImpressaoMapaDtoTipoQuebra;
  valorQuebra: ConfiguracaoImpressaoMapaDtoValorQuebra;
  separarPaleteFull: boolean;
  separarUnidades: boolean;
  exibirInfoCabecalho: ConfiguracaoImpressaoMapaDtoExibirInfoCabecalho;
  segregarFifo: ConfiguracaoImpressaoMapaDtoSegregarFifo;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  dataMaximaPercentual: number;
  createdAt: string;
  updatedAt: string;
  centerId: string;
  atribuidoPorId: ConfiguracaoImpressaoMapaDtoAtribuidoPorId;
  empresa: string;
  tipoImpressaoConferencia: ConfiguracaoImpressaoMapaDtoTipoImpressaoConferencia;
  ordemConferencia: ConfiguracaoImpressaoMapaDtoOrdemConferencia;
  ordemFifo: ConfiguracaoImpressaoMapaDtoOrdemFifo;
  ordemPaletes: ConfiguracaoImpressaoMapaDtoOrdemPaletes;
  ordemPicking: ConfiguracaoImpressaoMapaDtoOrdemPicking;
  ordemUnidades: ConfiguracaoImpressaoMapaDtoOrdemUnidades;
}
