/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */
import type { CorteMercadoriaGetDtoMotivo } from './corteMercadoriaGetDtoMotivo';
import type { CorteMercadoriaGetDtoDirecao } from './corteMercadoriaGetDtoDirecao';
import type { CorteMercadoriaGetDtoDescricao } from './corteMercadoriaGetDtoDescricao';
import type { CorteMercadoriaGetDtoRealizadoPorId } from './corteMercadoriaGetDtoRealizadoPorId';

export interface CorteMercadoriaGetDto {
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  id: number;
  produto: string;
  lote: string;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  unidades: number;
  motivo: CorteMercadoriaGetDtoMotivo;
  realizado: boolean;
  criadoEm: string;
  atualizadoEm: string;
  criadoPorId: string;
  transporteId: string;
  direcao: CorteMercadoriaGetDtoDirecao;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  caixas: number;
  centerId: string;
  descricao: CorteMercadoriaGetDtoDescricao;
  realizadoPorId: CorteMercadoriaGetDtoRealizadoPorId;
}
