/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */
import type { CorteMercadoriaDtoMotivo } from './corteMercadoriaDtoMotivo';
import type { CorteMercadoriaDtoDirecao } from './corteMercadoriaDtoDirecao';
import type { CorteMercadoriaDtoDescricao } from './corteMercadoriaDtoDescricao';
import type { CorteMercadoriaDtoRealizadoPorId } from './corteMercadoriaDtoRealizadoPorId';

export interface CorteMercadoriaDto {
  produto: string;
  lote: string;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  unidades: number;
  motivo: CorteMercadoriaDtoMotivo;
  realizado?: boolean;
  transporteId: string;
  direcao?: CorteMercadoriaDtoDirecao;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  caixas: number;
  descricao?: CorteMercadoriaDtoDescricao;
  realizadoPorId?: CorteMercadoriaDtoRealizadoPorId;
}
