/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */
import type { CreateCargaParadaDtoMotivo } from './createCargaParadaDtoMotivo';
import type { CreateCargaParadaDtoDataExpedicao } from './createCargaParadaDtoDataExpedicao';
import type { CreateCargaParadaDtoTransportId } from './createCargaParadaDtoTransportId';
import type { CreateCargaParadaDtoUserId } from './createCargaParadaDtoUserId';
import type { CreateCargaParadaDtoObservacao } from './createCargaParadaDtoObservacao';

export interface CreateCargaParadaDto {
  motivo?: CreateCargaParadaDtoMotivo;
  dataExpedicao?: CreateCargaParadaDtoDataExpedicao;
  transportId?: CreateCargaParadaDtoTransportId;
  userId?: CreateCargaParadaDtoUserId;
  observacao?: CreateCargaParadaDtoObservacao;
}
