/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */
import type { CreateUserDtoTurno } from './createUserDtoTurno';
import type { CreateUserDtoRole } from './createUserDtoRole';
import type { CreateUserDtoRoles } from './createUserDtoRoles';

export interface CreateUserDto {
  centerId: string;
  id: string;
  name: string;
  primeiroNome?: string;
  ultimoNome?: string;
  credencial?: string;
  turno: CreateUserDtoTurno;
  processo?: string;
  empresa: string;
  role?: CreateUserDtoRole;
  roles?: CreateUserDtoRoles;
}
