/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */
import type { CreateMovimentacaoDtoIdUsuario } from './createMovimentacaoDtoIdUsuario';
import type { CreateMovimentacaoDtoOrigem } from './createMovimentacaoDtoOrigem';
import type { CreateMovimentacaoDtoDestino } from './createMovimentacaoDtoDestino';
import type { CreateMovimentacaoDtoStatus } from './createMovimentacaoDtoStatus';
import type { CreateMovimentacaoDtoDataCriacao } from './createMovimentacaoDtoDataCriacao';
import type { CreateMovimentacaoDtoDataExecucao } from './createMovimentacaoDtoDataExecucao';
import type { CreateMovimentacaoDtoSku } from './createMovimentacaoDtoSku';
import type { CreateMovimentacaoDtoDescricao } from './createMovimentacaoDtoDescricao';
import type { CreateMovimentacaoDtoLote } from './createMovimentacaoDtoLote';
import type { CreateMovimentacaoDtoExecutadoPor } from './createMovimentacaoDtoExecutadoPor';
import type { CreateMovimentacaoDtoIniciado } from './createMovimentacaoDtoIniciado';

export interface CreateMovimentacaoDto {
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  idMov?: number;
  idUsuario?: CreateMovimentacaoDtoIdUsuario;
  idCentro: string;
  /** @maxLength 50 */
  palete: string;
  origem?: CreateMovimentacaoDtoOrigem;
  destino?: CreateMovimentacaoDtoDestino;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  prioridade: number;
  status?: CreateMovimentacaoDtoStatus;
  dataCriacao?: CreateMovimentacaoDtoDataCriacao;
  dataExecucao?: CreateMovimentacaoDtoDataExecucao;
  sku?: CreateMovimentacaoDtoSku;
  descricao?: CreateMovimentacaoDtoDescricao;
  lote?: CreateMovimentacaoDtoLote;
  executadoPor?: CreateMovimentacaoDtoExecutadoPor;
  iniciado?: CreateMovimentacaoDtoIniciado;
}
