/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */
import type { CreateContagemDtoSku } from './createContagemDtoSku';
import type { CreateContagemDtoDescricao } from './createContagemDtoDescricao';
import type { CreateContagemDtoDataValidade } from './createContagemDtoDataValidade';
import type { CreateContagemDtoLote } from './createContagemDtoLote';
import type { CreateContagemDtoPeso } from './createContagemDtoPeso';
import type { CreateContagemDtoCaixas } from './createContagemDtoCaixas';
import type { CreateContagemDtoQtdPalete } from './createContagemDtoQtdPalete';
import type { CreateContagemDtoCapacidadePalete } from './createContagemDtoCapacidadePalete';
import type { CreateContagemDtoArea } from './createContagemDtoArea';
import type { CreateContagemDtoCodigoBloqueio } from './createContagemDtoCodigoBloqueio';
import type { CreateContagemDtoValidado } from './createContagemDtoValidado';
import type { CreateContagemDtoAdicionarPor } from './createContagemDtoAdicionarPor';
import type { CreateContagemDtoContadoPor } from './createContagemDtoContadoPor';
import type { CreateContagemDtoHoraRegistro } from './createContagemDtoHoraRegistro';

export interface CreateContagemDto {
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  id?: number;
  dataRef: string;
  endereco: string;
  sku?: CreateContagemDtoSku;
  descricao?: CreateContagemDtoDescricao;
  dataValidade?: CreateContagemDtoDataValidade;
  lote?: CreateContagemDtoLote;
  peso?: CreateContagemDtoPeso;
  caixas?: CreateContagemDtoCaixas;
  qtdPalete?: CreateContagemDtoQtdPalete;
  capacidadePalete?: CreateContagemDtoCapacidadePalete;
  area?: CreateContagemDtoArea;
  centroId: string;
  codigoBloqueio?: CreateContagemDtoCodigoBloqueio;
  validado?: CreateContagemDtoValidado;
  adicionarPor?: CreateContagemDtoAdicionarPor;
  contadoPor?: CreateContagemDtoContadoPor;
  horaRegistro?: CreateContagemDtoHoraRegistro;
}
