/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */
import type { CreateAnomaliaContagemLiteDtoSku } from './createAnomaliaContagemLiteDtoSku';
import type { CreateAnomaliaContagemLiteDtoLote } from './createAnomaliaContagemLiteDtoLote';
import type { CreateAnomaliaContagemLiteDtoQuantidade } from './createAnomaliaContagemLiteDtoQuantidade';
import type { CreateAnomaliaContagemLiteDtoPeso } from './createAnomaliaContagemLiteDtoPeso';
import type { CreateAnomaliaContagemLiteDtoDataReferencia } from './createAnomaliaContagemLiteDtoDataReferencia';
import type { CreateAnomaliaContagemLiteDtoAddPor } from './createAnomaliaContagemLiteDtoAddPor';

export interface CreateAnomaliaContagemLiteDto {
  sku?: CreateAnomaliaContagemLiteDtoSku;
  lote?: CreateAnomaliaContagemLiteDtoLote;
  quantidade?: CreateAnomaliaContagemLiteDtoQuantidade;
  peso?: CreateAnomaliaContagemLiteDtoPeso;
  dataReferencia?: CreateAnomaliaContagemLiteDtoDataReferencia;
  addPor?: CreateAnomaliaContagemLiteDtoAddPor;
}
