/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */
import type { CreateTransporteItemDtoStatus } from './createTransporteItemDtoStatus';
import type { CreateTransporteItemDtoObs } from './createTransporteItemDtoObs';
import type { CreateTransporteItemDtoCarregamento } from './createTransporteItemDtoCarregamento';
import type { CreateTransporteItemDtoConferencia } from './createTransporteItemDtoConferencia';
import type { CreateTransporteItemDtoSeparacao } from './createTransporteItemDtoSeparacao';
import type { CreateTransporteItemDtoCargaParada } from './createTransporteItemDtoCargaParada';

export interface CreateTransporteItemDto {
  numeroTransporte: string;
  status: CreateTransporteItemDtoStatus;
  nomeRota: string;
  nomeTransportadora: string;
  placa: string;
  dataExpedicao: string;
  centerId: string;
  obs: CreateTransporteItemDtoObs;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  prioridade: number;
  carregamento: CreateTransporteItemDtoCarregamento;
  conferencia: CreateTransporteItemDtoConferencia;
  separacao: CreateTransporteItemDtoSeparacao;
  cargaParada: CreateTransporteItemDtoCargaParada;
}
