/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */
import type { DemandCompactDtoItemsItemConferenciasItemLote } from './demandCompactDtoItemsItemConferenciasItemLote';

export type DemandCompactDtoItemsItemConferenciasItem = {
  id: string;
  codigoProduto: string;
  lote?: DemandCompactDtoItemsItemConferenciasItemLote;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  caixas?: number;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  unidades?: number;
};
