/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */
import type { DemandCompactDtoItemsItemAnomaliasItemNatureza } from './demandCompactDtoItemsItemAnomaliasItemNatureza';
import type { DemandCompactDtoItemsItemAnomaliasItemCausa } from './demandCompactDtoItemsItemAnomaliasItemCausa';
import type { DemandCompactDtoItemsItemAnomaliasItemObservacoes } from './demandCompactDtoItemsItemAnomaliasItemObservacoes';

export type DemandCompactDtoItemsItemAnomaliasItem = {
  id: string;
  natureza?: DemandCompactDtoItemsItemAnomaliasItemNatureza;
  tipo: string;
  causa?: DemandCompactDtoItemsItemAnomaliasItemCausa;
  fotos: string[];
  observacoes?: DemandCompactDtoItemsItemAnomaliasItemObservacoes;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  caixasDanificadas?: number;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  unidadesDanificadas?: number;
  lote: string;
};
