/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */
import type { DemandaCreateDataComPaletesIdsProcesso } from './demandaCreateDataComPaletesIdsProcesso';
import type { DemandaCreateDataComPaletesIdsFim } from './demandaCreateDataComPaletesIdsFim';
import type { DemandaCreateDataComPaletesIdsStatus } from './demandaCreateDataComPaletesIdsStatus';
import type { DemandaCreateDataComPaletesIdsTurno } from './demandaCreateDataComPaletesIdsTurno';
import type { DemandaCreateDataComPaletesIdsObs } from './demandaCreateDataComPaletesIdsObs';

export interface DemandaCreateDataComPaletesIds {
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  id?: number;
  processo: DemandaCreateDataComPaletesIdsProcesso;
  fim?: DemandaCreateDataComPaletesIdsFim;
  status?: DemandaCreateDataComPaletesIdsStatus;
  turno: DemandaCreateDataComPaletesIdsTurno;
  funcionarioId: string;
  criadoEm?: string;
  centerId: string;
  obs?: DemandaCreateDataComPaletesIdsObs;
  dataExpedicao?: string;
  paletesIds?: string[];
}
