/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */
import type { DemandCompactDtoChecklistAnyOfTemperaturaTrunk } from './demandCompactDtoChecklistAnyOfTemperaturaTrunk';
import type { DemandCompactDtoChecklistAnyOfTemperaturaProduto } from './demandCompactDtoChecklistAnyOfTemperaturaProduto';
import type { DemandCompactDtoChecklistAnyOfObservacoes } from './demandCompactDtoChecklistAnyOfObservacoes';

export type DemandCompactDtoChecklistAnyOf = {
  temperaturaTrunk?: DemandCompactDtoChecklistAnyOfTemperaturaTrunk;
  temperaturaProduto?: DemandCompactDtoChecklistAnyOfTemperaturaProduto;
  observacoes?: DemandCompactDtoChecklistAnyOfObservacoes;
};
