/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */
import type { DemandCompactDtoStatus } from './demandCompactDtoStatus';
import type { DemandCompactDtoDoca } from './demandCompactDtoDoca';
import type { DemandCompactDtoResponsavel } from './demandCompactDtoResponsavel';
import type { DemandCompactDtoDocaRecepcao } from './demandCompactDtoDocaRecepcao';
import type { DemandCompactDtoIsSegregada } from './demandCompactDtoIsSegregada';
import type { DemandCompactDtoChecklist } from './demandCompactDtoChecklist';
import type { DemandCompactDtoItemsItem } from './demandCompactDtoItemsItem';
import type { DemandCompactDtoSync } from './demandCompactDtoSync';

export interface DemandCompactDto {
  id: string;
  status: DemandCompactDtoStatus;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  paletesEsperadas?: number;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  paletesReceptadas?: number;
  doca?: DemandCompactDtoDoca;
  dataGeracao: string;
  responsavel?: DemandCompactDtoResponsavel;
  placa: string;
  docaRecepcao?: DemandCompactDtoDocaRecepcao;
  isSegregada?: DemandCompactDtoIsSegregada;
  checklist?: DemandCompactDtoChecklist;
  items: DemandCompactDtoItemsItem[];
  sync: DemandCompactDtoSync;
}
