/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */
import type { DemandCompactDtoItemsItemConferenciasItem } from './demandCompactDtoItemsItemConferenciasItem';
import type { DemandCompactDtoItemsItemAnomaliasItem } from './demandCompactDtoItemsItemAnomaliasItem';

export type DemandCompactDtoItemsItem = {
  id: string;
  codigoProduto: string;
  descricao: string;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  caixasEsperadas?: number;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  unidadesEsperadas?: number;
  isReentrega?: boolean;
  conferencias: DemandCompactDtoItemsItemConferenciasItem[];
  anomalias: DemandCompactDtoItemsItemAnomaliasItem[];
  extra?: boolean;
};
