/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */
import type { EngineRuleGetDtoDescription } from './engineRuleGetDtoDescription';
import type { EngineRuleGetDtoConditions } from './engineRuleGetDtoConditions';
import type { EngineRuleGetDtoCreatedBy } from './engineRuleGetDtoCreatedBy';

export interface EngineRuleGetDto {
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  id: number;
  name: string;
  description: EngineRuleGetDtoDescription;
  centerId: string;
  enabled: boolean;
  conditions: EngineRuleGetDtoConditions;
  createdBy: EngineRuleGetDtoCreatedBy;
  createdAt: string;
  updatedAt: string;
  processo: string;
  criadoPorId: string;
}
