/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */
import type { GetAnomaliaContagemDtoEndereco } from './getAnomaliaContagemDtoEndereco';
import type { GetAnomaliaContagemDtoCentroId } from './getAnomaliaContagemDtoCentroId';
import type { GetAnomaliaContagemDtoSku } from './getAnomaliaContagemDtoSku';
import type { GetAnomaliaContagemDtoLote } from './getAnomaliaContagemDtoLote';
import type { GetAnomaliaContagemDtoQuantidade } from './getAnomaliaContagemDtoQuantidade';
import type { GetAnomaliaContagemDtoPeso } from './getAnomaliaContagemDtoPeso';
import type { GetAnomaliaContagemDtoDataReferencia } from './getAnomaliaContagemDtoDataReferencia';
import type { GetAnomaliaContagemDtoAddPor } from './getAnomaliaContagemDtoAddPor';

export interface GetAnomaliaContagemDto {
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  id: number;
  endereco: GetAnomaliaContagemDtoEndereco;
  centroId: GetAnomaliaContagemDtoCentroId;
  sku: GetAnomaliaContagemDtoSku;
  lote: GetAnomaliaContagemDtoLote;
  quantidade: GetAnomaliaContagemDtoQuantidade;
  peso: GetAnomaliaContagemDtoPeso;
  dataReferencia: GetAnomaliaContagemDtoDataReferencia;
  addPor: GetAnomaliaContagemDtoAddPor;
}
