/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */
import type { GetAnomaliasByDemandaDtoUuid } from './getAnomaliasByDemandaDtoUuid';
import type { GetAnomaliasByDemandaDtoTipo } from './getAnomaliasByDemandaDtoTipo';
import type { GetAnomaliasByDemandaDtoNatureza } from './getAnomaliasByDemandaDtoNatureza';
import type { GetAnomaliasByDemandaDtoCausa } from './getAnomaliasByDemandaDtoCausa';

export interface GetAnomaliasByDemandaDto {
  id: number;
  demandaId: number;
  uuid?: GetAnomaliasByDemandaDtoUuid;
  sku: string;
  lote: string;
  tipo?: GetAnomaliasByDemandaDtoTipo;
  natureza?: GetAnomaliasByDemandaDtoNatureza;
  causa?: GetAnomaliasByDemandaDtoCausa;
  descricao: string;
  quantidadeCaixas: number;
  quantidadeUnidades: number;
  imagens: string[];
}
