/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */
import type { GetContagemDtoSku } from './getContagemDtoSku';
import type { GetContagemDtoDescricao } from './getContagemDtoDescricao';
import type { GetContagemDtoDataValidade } from './getContagemDtoDataValidade';
import type { GetContagemDtoLote } from './getContagemDtoLote';
import type { GetContagemDtoPeso } from './getContagemDtoPeso';
import type { GetContagemDtoCaixas } from './getContagemDtoCaixas';
import type { GetContagemDtoQtdPalete } from './getContagemDtoQtdPalete';
import type { GetContagemDtoCapacidadePalete } from './getContagemDtoCapacidadePalete';
import type { GetContagemDtoArea } from './getContagemDtoArea';
import type { GetContagemDtoCodigoBloqueio } from './getContagemDtoCodigoBloqueio';
import type { GetContagemDtoValidado } from './getContagemDtoValidado';
import type { GetContagemDtoAdicionarPor } from './getContagemDtoAdicionarPor';
import type { GetContagemDtoContadoPor } from './getContagemDtoContadoPor';
import type { GetContagemDtoHoraRegistro } from './getContagemDtoHoraRegistro';

export interface GetContagemDto {
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  id: number;
  dataRef: string;
  endereco: string;
  sku: GetContagemDtoSku;
  descricao: GetContagemDtoDescricao;
  dataValidade: GetContagemDtoDataValidade;
  lote: GetContagemDtoLote;
  peso: GetContagemDtoPeso;
  caixas: GetContagemDtoCaixas;
  qtdPalete: GetContagemDtoQtdPalete;
  capacidadePalete: GetContagemDtoCapacidadePalete;
  area: GetContagemDtoArea;
  centroId: string;
  codigoBloqueio: GetContagemDtoCodigoBloqueio;
  validado: GetContagemDtoValidado;
  adicionarPor: GetContagemDtoAdicionarPor;
  contadoPor: GetContagemDtoContadoPor;
  horaRegistro: GetContagemDtoHoraRegistro;
}
