/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */

export type GetItensDemandaDtoTipo = typeof GetItensDemandaDtoTipo[keyof typeof GetItensDemandaDtoTipo];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetItensDemandaDtoTipo = {
  CONTABIL: 'CONTABIL',
  FISICO: 'FISICO',
} as const;
