/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */
import type { GetItensDemandaDtoTipo } from './getItensDemandaDtoTipo';
import type { GetItensDemandaDtoTipoDevolucao } from './getItensDemandaDtoTipoDevolucao';

export interface GetItensDemandaDto {
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  id?: number;
  sku: string;
  descricao: string;
  lote?: string;
  fabricacao?: string;
  sif?: string;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  quantidadeCaixas?: number;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  quantidadeUnidades?: number;
  tipo: GetItensDemandaDtoTipo;
  tipoDevolucao: GetItensDemandaDtoTipoDevolucao;
  devolucaoNotasId?: string;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  demandaId: number;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  avariaCaixas?: number;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  avariaUnidades?: number;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  nota_id?: number;
}
