/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */
import type { GetMovimentacaoDtoIdUsuario } from './getMovimentacaoDtoIdUsuario';
import type { GetMovimentacaoDtoOrigem } from './getMovimentacaoDtoOrigem';
import type { GetMovimentacaoDtoDestino } from './getMovimentacaoDtoDestino';
import type { GetMovimentacaoDtoStatus } from './getMovimentacaoDtoStatus';
import type { GetMovimentacaoDtoDataCriacao } from './getMovimentacaoDtoDataCriacao';
import type { GetMovimentacaoDtoDataExecucao } from './getMovimentacaoDtoDataExecucao';
import type { GetMovimentacaoDtoSku } from './getMovimentacaoDtoSku';
import type { GetMovimentacaoDtoDescricao } from './getMovimentacaoDtoDescricao';
import type { GetMovimentacaoDtoLote } from './getMovimentacaoDtoLote';
import type { GetMovimentacaoDtoExecutadoPor } from './getMovimentacaoDtoExecutadoPor';
import type { GetMovimentacaoDtoIniciado } from './getMovimentacaoDtoIniciado';

export interface GetMovimentacaoDto {
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  idMov: number;
  idUsuario: GetMovimentacaoDtoIdUsuario;
  idCentro: string;
  /** @maxLength 50 */
  palete: string;
  origem: GetMovimentacaoDtoOrigem;
  destino: GetMovimentacaoDtoDestino;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  prioridade: number;
  status: GetMovimentacaoDtoStatus;
  dataCriacao: GetMovimentacaoDtoDataCriacao;
  dataExecucao: GetMovimentacaoDtoDataExecucao;
  sku: GetMovimentacaoDtoSku;
  descricao: GetMovimentacaoDtoDescricao;
  lote: GetMovimentacaoDtoLote;
  executadoPor: GetMovimentacaoDtoExecutadoPor;
  iniciado: GetMovimentacaoDtoIniciado;
}
