/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */
import type { GetNotasDtoEmpresa } from './getNotasDtoEmpresa';
import type { GetNotasDtoDescMotivoDevolucao } from './getNotasDtoDescMotivoDevolucao';
import type { GetNotasDtoNfParcial } from './getNotasDtoNfParcial';
import type { GetNotasDtoIdViagemRavex } from './getNotasDtoIdViagemRavex';
import type { GetNotasDtoTipo } from './getNotasDtoTipo';

export interface GetNotasDto {
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  id: number;
  empresa: GetNotasDtoEmpresa;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  devolucaoDemandaId: number;
  notaFiscal: string;
  motivoDevolucao: string;
  descMotivoDevolucao: GetNotasDtoDescMotivoDevolucao;
  nfParcial: GetNotasDtoNfParcial;
  idViagemRavex: GetNotasDtoIdViagemRavex;
  criadoEm: string;
  atualizadoEm: string;
  tipo: GetNotasDtoTipo;
}
