/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */
import type { GetTransporteDtoStatus } from './getTransporteDtoStatus';
import type { GetTransporteDtoObs } from './getTransporteDtoObs';
import type { GetTransporteDtoCarregamento } from './getTransporteDtoCarregamento';
import type { GetTransporteDtoConferencia } from './getTransporteDtoConferencia';
import type { GetTransporteDtoSeparacao } from './getTransporteDtoSeparacao';
import type { GetTransporteDtoCargaParada } from './getTransporteDtoCargaParada';

export interface GetTransporteDto {
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  id: number;
  numeroTransporte: string;
  status: GetTransporteDtoStatus;
  nomeRota: string;
  nomeTransportadora: string;
  placa: string;
  criadoEm: string;
  atualizadoEm: string;
  cadastradoPorId: string;
  dataExpedicao: string;
  centerId: string;
  obs: GetTransporteDtoObs;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  prioridade: number;
  carregamento: GetTransporteDtoCarregamento;
  conferencia: GetTransporteDtoConferencia;
  separacao: GetTransporteDtoSeparacao;
  cargaParada: GetTransporteDtoCargaParada;
}
