/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */
import type { ListarDemandasDtoIdTransportadora } from './listarDemandasDtoIdTransportadora';
import type { ListarDemandasDtoTelefone } from './listarDemandasDtoTelefone';
import type { ListarDemandasDtoQuantidadePaletes } from './listarDemandasDtoQuantidadePaletes';
import type { ListarDemandasDtoDoca } from './listarDemandasDtoDoca';
import type { ListarDemandasDtoConferenteId } from './listarDemandasDtoConferenteId';
import type { ListarDemandasDtoStatus } from './listarDemandasDtoStatus';
import type { ListarDemandasDtoFechouComAnomalia } from './listarDemandasDtoFechouComAnomalia';
import type { ListarDemandasDtoLiberadoParaConferenciaEm } from './listarDemandasDtoLiberadoParaConferenciaEm';
import type { ListarDemandasDtoInicioConferenciaEm } from './listarDemandasDtoInicioConferenciaEm';
import type { ListarDemandasDtoFimConferenciaEm } from './listarDemandasDtoFimConferenciaEm';
import type { ListarDemandasDtoFinalizadoEm } from './listarDemandasDtoFinalizadoEm';
import type { ListarDemandasDtoViagemId } from './listarDemandasDtoViagemId';

export interface ListarDemandasDto {
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  id: number;
  placa: string;
  motorista: string;
  idTransportadora: ListarDemandasDtoIdTransportadora;
  telefone: ListarDemandasDtoTelefone;
  cargaSegregada: boolean;
  quantidadePaletes: ListarDemandasDtoQuantidadePaletes;
  doca: ListarDemandasDtoDoca;
  centerId: string;
  adicionadoPorId: string;
  conferenteId: ListarDemandasDtoConferenteId;
  criadoEm: string;
  atualizadoEm: string;
  status: ListarDemandasDtoStatus;
  fechouComAnomalia: ListarDemandasDtoFechouComAnomalia;
  liberadoParaConferenciaEm: ListarDemandasDtoLiberadoParaConferenciaEm;
  inicioConferenciaEm: ListarDemandasDtoInicioConferenciaEm;
  fimConferenciaEm: ListarDemandasDtoFimConferenciaEm;
  finalizadoEm: ListarDemandasDtoFinalizadoEm;
  senha: string;
  viagemId: ListarDemandasDtoViagemId;
}
