/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */
import type { PaleteCreateDataDtoTipoProcesso } from './paleteCreateDataDtoTipoProcesso';
import type { PaleteCreateDataDtoDemandaId } from './paleteCreateDataDtoDemandaId';
import type { PaleteCreateDataDtoStatus } from './paleteCreateDataDtoStatus';
import type { PaleteCreateDataDtoFim } from './paleteCreateDataDtoFim';
import type { PaleteCreateDataDtoInicio } from './paleteCreateDataDtoInicio';

export interface PaleteCreateDataDto {
  id: string;
  empresa: string;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  quantidadeCaixas: number;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  quantidadeUnidades: number;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  quantidadePaletes: number;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  enderecoVisitado: number;
  segmento: string;
  transporteId: string;
  tipoProcesso?: PaleteCreateDataDtoTipoProcesso;
  criadoEm?: string;
  demandaId?: PaleteCreateDataDtoDemandaId;
  status?: PaleteCreateDataDtoStatus;
  validado?: boolean;
  fim?: PaleteCreateDataDtoFim;
  inicio?: PaleteCreateDataDtoInicio;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  totalCaixas?: number;
  /**
   * @minimum -140737488355328
   * @maximum 140737488355327
   */
  pesoLiquido?: number;
}
