/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */
import type { PaleteGetDataTransporteDtoTipoProcesso } from './paleteGetDataTransporteDtoTipoProcesso';

export interface PaleteGetDataTransporteDto {
  palete_id: string;
  empresa: string;
  quantidadeCaixas: number;
  quantidadeUnidades: number;
  quantidadePaletes: number;
  enderecoVisitado: number;
  segmento: string;
  tipoProcesso: PaleteGetDataTransporteDtoTipoProcesso;
  status_palete: string;
  transporteId: string;
  centerId: string;
  data_expedicao: string;
}
