/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */
import type { PausaGeralCreateDataDtoFim } from './pausaGeralCreateDataDtoFim';
import type { PausaGeralCreateDataDtoProcesso } from './pausaGeralCreateDataDtoProcesso';
import type { PausaGeralCreateDataDtoTurno } from './pausaGeralCreateDataDtoTurno';

export interface PausaGeralCreateDataDto {
  inicio: string;
  fim?: PausaGeralCreateDataDtoFim;
  motivo: string;
  centerId: string;
  processo: PausaGeralCreateDataDtoProcesso;
  turno: PausaGeralCreateDataDtoTurno;
  criadoEm?: string;
  segmento: string;
}
