/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */
import type { ProdutividadeDiaDiaGetDataDtoTop5ProdutividadeItemFuncionarioid } from './produtividadeDiaDiaGetDataDtoTop5ProdutividadeItemFuncionarioid';
import type { ProdutividadeDiaDiaGetDataDtoTop5ProdutividadeItemFuncionarionome } from './produtividadeDiaDiaGetDataDtoTop5ProdutividadeItemFuncionarionome';
import type { ProdutividadeDiaDiaGetDataDtoTop5ProdutividadeItemProcesso } from './produtividadeDiaDiaGetDataDtoTop5ProdutividadeItemProcesso';
import type { ProdutividadeDiaDiaGetDataDtoTop5ProdutividadeItemCenterid } from './produtividadeDiaDiaGetDataDtoTop5ProdutividadeItemCenterid';
import type { ProdutividadeDiaDiaGetDataDtoTop5ProdutividadeItemDataregistro } from './produtividadeDiaDiaGetDataDtoTop5ProdutividadeItemDataregistro';
import type { ProdutividadeDiaDiaGetDataDtoTop5ProdutividadeItemPeriodoInicio } from './produtividadeDiaDiaGetDataDtoTop5ProdutividadeItemPeriodoInicio';
import type { ProdutividadeDiaDiaGetDataDtoTop5ProdutividadeItemPeriodoFim } from './produtividadeDiaDiaGetDataDtoTop5ProdutividadeItemPeriodoFim';
import type { ProdutividadeDiaDiaGetDataDtoTop5ProdutividadeItemTotalTempoPausa } from './produtividadeDiaDiaGetDataDtoTop5ProdutividadeItemTotalTempoPausa';
import type { ProdutividadeDiaDiaGetDataDtoTop5ProdutividadeItemTotalCaixas } from './produtividadeDiaDiaGetDataDtoTop5ProdutividadeItemTotalCaixas';
import type { ProdutividadeDiaDiaGetDataDtoTop5ProdutividadeItemTempoTotal } from './produtividadeDiaDiaGetDataDtoTop5ProdutividadeItemTempoTotal';
import type { ProdutividadeDiaDiaGetDataDtoTop5ProdutividadeItemTotalDemandas } from './produtividadeDiaDiaGetDataDtoTop5ProdutividadeItemTotalDemandas';
import type { ProdutividadeDiaDiaGetDataDtoTop5ProdutividadeItemTotalEnderecosVisitados } from './produtividadeDiaDiaGetDataDtoTop5ProdutividadeItemTotalEnderecosVisitados';
import type { ProdutividadeDiaDiaGetDataDtoTop5ProdutividadeItemTempoTrabalhado } from './produtividadeDiaDiaGetDataDtoTop5ProdutividadeItemTempoTrabalhado';
import type { ProdutividadeDiaDiaGetDataDtoTop5ProdutividadeItemProdutividadeCaixaPorHora } from './produtividadeDiaDiaGetDataDtoTop5ProdutividadeItemProdutividadeCaixaPorHora';
import type { ProdutividadeDiaDiaGetDataDtoTop5ProdutividadeItemMediaEnderecosPorDemanda } from './produtividadeDiaDiaGetDataDtoTop5ProdutividadeItemMediaEnderecosPorDemanda';
import type { ProdutividadeDiaDiaGetDataDtoTop5ProdutividadeItemSegmento } from './produtividadeDiaDiaGetDataDtoTop5ProdutividadeItemSegmento';

export type ProdutividadeDiaDiaGetDataDtoTop5ProdutividadeItem = {
  funcionarioid: ProdutividadeDiaDiaGetDataDtoTop5ProdutividadeItemFuncionarioid;
  funcionarionome: ProdutividadeDiaDiaGetDataDtoTop5ProdutividadeItemFuncionarionome;
  processo: ProdutividadeDiaDiaGetDataDtoTop5ProdutividadeItemProcesso;
  centerid: ProdutividadeDiaDiaGetDataDtoTop5ProdutividadeItemCenterid;
  dataregistro: ProdutividadeDiaDiaGetDataDtoTop5ProdutividadeItemDataregistro;
  periodoInicio: ProdutividadeDiaDiaGetDataDtoTop5ProdutividadeItemPeriodoInicio;
  periodoFim: ProdutividadeDiaDiaGetDataDtoTop5ProdutividadeItemPeriodoFim;
  totalTempoPausa: ProdutividadeDiaDiaGetDataDtoTop5ProdutividadeItemTotalTempoPausa;
  totalCaixas: ProdutividadeDiaDiaGetDataDtoTop5ProdutividadeItemTotalCaixas;
  tempoTotal: ProdutividadeDiaDiaGetDataDtoTop5ProdutividadeItemTempoTotal;
  totalDemandas: ProdutividadeDiaDiaGetDataDtoTop5ProdutividadeItemTotalDemandas;
  totalEnderecosVisitados: ProdutividadeDiaDiaGetDataDtoTop5ProdutividadeItemTotalEnderecosVisitados;
  tempoTrabalhado: ProdutividadeDiaDiaGetDataDtoTop5ProdutividadeItemTempoTrabalhado;
  produtividadeCaixaPorHora: ProdutividadeDiaDiaGetDataDtoTop5ProdutividadeItemProdutividadeCaixaPorHora;
  mediaEnderecosPorDemanda: ProdutividadeDiaDiaGetDataDtoTop5ProdutividadeItemMediaEnderecosPorDemanda;
  segmento: ProdutividadeDiaDiaGetDataDtoTop5ProdutividadeItemSegmento;
};
