/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */
import type { ProdutividadeDiaDiaGetDataDtoProdutividadeItem } from './produtividadeDiaDiaGetDataDtoProdutividadeItem';
import type { ProdutividadeDiaDiaGetDataDtoTop5ProdutividadeItem } from './produtividadeDiaDiaGetDataDtoTop5ProdutividadeItem';
import type { ProdutividadeDiaDiaGetDataDtoBottom5ProdutividadeItem } from './produtividadeDiaDiaGetDataDtoBottom5ProdutividadeItem';
import type { ProdutividadeDiaDiaGetDataDtoProdutividadeProcessoItem } from './produtividadeDiaDiaGetDataDtoProdutividadeProcessoItem';
import type { ProdutividadeDiaDiaGetDataDtoListaProdutividadePorFuncionarioItem } from './produtividadeDiaDiaGetDataDtoListaProdutividadePorFuncionarioItem';

export interface ProdutividadeDiaDiaGetDataDto {
  produtividade: ProdutividadeDiaDiaGetDataDtoProdutividadeItem[];
  top5Produtividade: ProdutividadeDiaDiaGetDataDtoTop5ProdutividadeItem[];
  bottom5Produtividade: ProdutividadeDiaDiaGetDataDtoBottom5ProdutividadeItem[];
  produtividadeProcesso: ProdutividadeDiaDiaGetDataDtoProdutividadeProcessoItem[];
  listaProdutividadePorFuncionario: ProdutividadeDiaDiaGetDataDtoListaProdutividadePorFuncionarioItem[];
}
