/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */
import type { ProdutividadeGetDataDtoFim } from './produtividadeGetDataDtoFim';
import type { ProdutividadeGetDataDtoObs } from './produtividadeGetDataDtoObs';

export interface ProdutividadeGetDataDto {
  idDemanda: number;
  empresa: string;
  centerId: string;
  processo: string;
  segmento: string;
  inicio: string;
  fim: ProdutividadeGetDataDtoFim;
  cadastradoPorId: string;
  turno: string;
  funcionarioId: string;
  nomeFuncionario: string;
  statusDemanda: string;
  caixas: number;
  unidades: number;
  paletes: number;
  visitas: number;
  pausas: number;
  tempoTrabalhado: number;
  tempoPausas: number;
  tempoTotal: number;
  produtividade: number;
  obs: ProdutividadeGetDataDtoObs;
}
