/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */
import type { ProdutividadeDiaDiaGetDataDtoProdutividadeItemCenterid } from './produtividadeDiaDiaGetDataDtoProdutividadeItemCenterid';
import type { ProdutividadeDiaDiaGetDataDtoProdutividadeItemData } from './produtividadeDiaDiaGetDataDtoProdutividadeItemData';
import type { ProdutividadeDiaDiaGetDataDtoProdutividadeItemTotalTempoPausa } from './produtividadeDiaDiaGetDataDtoProdutividadeItemTotalTempoPausa';
import type { ProdutividadeDiaDiaGetDataDtoProdutividadeItemTotalCaixas } from './produtividadeDiaDiaGetDataDtoProdutividadeItemTotalCaixas';
import type { ProdutividadeDiaDiaGetDataDtoProdutividadeItemTempoTotal } from './produtividadeDiaDiaGetDataDtoProdutividadeItemTempoTotal';
import type { ProdutividadeDiaDiaGetDataDtoProdutividadeItemTempoTrabalhado } from './produtividadeDiaDiaGetDataDtoProdutividadeItemTempoTrabalhado';
import type { ProdutividadeDiaDiaGetDataDtoProdutividadeItemProcesso } from './produtividadeDiaDiaGetDataDtoProdutividadeItemProcesso';
import type { ProdutividadeDiaDiaGetDataDtoProdutividadeItemProdutividadeCaixaPorHora } from './produtividadeDiaDiaGetDataDtoProdutividadeItemProdutividadeCaixaPorHora';

export type ProdutividadeDiaDiaGetDataDtoProdutividadeItem = {
  centerid: ProdutividadeDiaDiaGetDataDtoProdutividadeItemCenterid;
  data: ProdutividadeDiaDiaGetDataDtoProdutividadeItemData;
  totalTempoPausa: ProdutividadeDiaDiaGetDataDtoProdutividadeItemTotalTempoPausa;
  totalCaixas: ProdutividadeDiaDiaGetDataDtoProdutividadeItemTotalCaixas;
  tempoTotal: ProdutividadeDiaDiaGetDataDtoProdutividadeItemTempoTotal;
  tempoTrabalhado: ProdutividadeDiaDiaGetDataDtoProdutividadeItemTempoTrabalhado;
  processo: ProdutividadeDiaDiaGetDataDtoProdutividadeItemProcesso;
  produtividadeCaixaPorHora: ProdutividadeDiaDiaGetDataDtoProdutividadeItemProdutividadeCaixaPorHora;
};
