/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */
import type { ProdutividadeWithPausaAndPaleteDtoListaPausasItemFim } from './produtividadeWithPausaAndPaleteDtoListaPausasItemFim';
import type { ProdutividadeWithPausaAndPaleteDtoListaPausasItemDescricao } from './produtividadeWithPausaAndPaleteDtoListaPausasItemDescricao';

export type ProdutividadeWithPausaAndPaleteDtoListaPausasItem = {
  id: number;
  inicio: string;
  fim: ProdutividadeWithPausaAndPaleteDtoListaPausasItemFim;
  motivo: string;
  descricao: ProdutividadeWithPausaAndPaleteDtoListaPausasItemDescricao;
  demandaId: number;
  registradoPorId: string;
};
