/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */
import type { ProdutividadeWithPausaAndPaleteDtoListaPaletesItemInicio } from './produtividadeWithPausaAndPaleteDtoListaPaletesItemInicio';
import type { ProdutividadeWithPausaAndPaleteDtoListaPaletesItemFim } from './produtividadeWithPausaAndPaleteDtoListaPaletesItemFim';
import type { ProdutividadeWithPausaAndPaleteDtoListaPaletesItemDemandaId } from './produtividadeWithPausaAndPaleteDtoListaPaletesItemDemandaId';

export type ProdutividadeWithPausaAndPaleteDtoListaPaletesItem = {
  id: string;
  empresa: string;
  quantidadeCaixas: number;
  quantidadeUnidades: number;
  quantidadePaletes: number;
  enderecoVisitado: number;
  segmento: string;
  transporteId: string;
  inicio: ProdutividadeWithPausaAndPaleteDtoListaPaletesItemInicio;
  fim: ProdutividadeWithPausaAndPaleteDtoListaPaletesItemFim;
  tipoProcesso: string;
  criadoEm: string;
  atualizadoEm: string;
  demandaId: ProdutividadeWithPausaAndPaleteDtoListaPaletesItemDemandaId;
  status: string;
  validado: boolean;
  criadoPorId: string;
};
