/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */
import type { ProdutoDtoTipoPeso } from './produtoDtoTipoPeso';
import type { ProdutoDtoSegmento } from './produtoDtoSegmento';
import type { ProdutoDtoEmpresa } from './produtoDtoEmpresa';

export interface ProdutoDto {
  codDum?: string;
  codEan?: string;
  /** @minLength 1 */
  sku: string;
  /** @minLength 1 */
  descricao: string;
  /**
   * @maximum 9007199254740991
   */
  shelf: number;
  tipoPeso: ProdutoDtoTipoPeso;
  /** @minLength 1 */
  pesoLiquidoCaixa: string;
  /** @minLength 1 */
  pesoLiquidoUnidade: string;
  /**
   * @maximum 9007199254740991
   */
  unPorCaixa: number;
  /**
   * @maximum 9007199254740991
   */
  caixaPorPallet: number;
  segmento: ProdutoDtoSegmento;
  empresa: ProdutoDtoEmpresa;
  criadoEm?: string;
}
