/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */
import type { ProdutividadeDiaDiaGetDataDtoProdutividadeProcessoItemCenterid } from './produtividadeDiaDiaGetDataDtoProdutividadeProcessoItemCenterid';
import type { ProdutividadeDiaDiaGetDataDtoProdutividadeProcessoItemProcesso } from './produtividadeDiaDiaGetDataDtoProdutividadeProcessoItemProcesso';
import type { ProdutividadeDiaDiaGetDataDtoProdutividadeProcessoItemTurno } from './produtividadeDiaDiaGetDataDtoProdutividadeProcessoItemTurno';
import type { ProdutividadeDiaDiaGetDataDtoProdutividadeProcessoItemCriadoem } from './produtividadeDiaDiaGetDataDtoProdutividadeProcessoItemCriadoem';
import type { ProdutividadeDiaDiaGetDataDtoProdutividadeProcessoItemPeriodoInicio } from './produtividadeDiaDiaGetDataDtoProdutividadeProcessoItemPeriodoInicio';
import type { ProdutividadeDiaDiaGetDataDtoProdutividadeProcessoItemPeriodoFim } from './produtividadeDiaDiaGetDataDtoProdutividadeProcessoItemPeriodoFim';
import type { ProdutividadeDiaDiaGetDataDtoProdutividadeProcessoItemTotalTempoPausa } from './produtividadeDiaDiaGetDataDtoProdutividadeProcessoItemTotalTempoPausa';
import type { ProdutividadeDiaDiaGetDataDtoProdutividadeProcessoItemTotalCaixas } from './produtividadeDiaDiaGetDataDtoProdutividadeProcessoItemTotalCaixas';
import type { ProdutividadeDiaDiaGetDataDtoProdutividadeProcessoItemTempoTotal } from './produtividadeDiaDiaGetDataDtoProdutividadeProcessoItemTempoTotal';
import type { ProdutividadeDiaDiaGetDataDtoProdutividadeProcessoItemTotalDemandas } from './produtividadeDiaDiaGetDataDtoProdutividadeProcessoItemTotalDemandas';
import type { ProdutividadeDiaDiaGetDataDtoProdutividadeProcessoItemTotalEnderecosVisitados } from './produtividadeDiaDiaGetDataDtoProdutividadeProcessoItemTotalEnderecosVisitados';
import type { ProdutividadeDiaDiaGetDataDtoProdutividadeProcessoItemTempoTrabalhado } from './produtividadeDiaDiaGetDataDtoProdutividadeProcessoItemTempoTrabalhado';
import type { ProdutividadeDiaDiaGetDataDtoProdutividadeProcessoItemProdutividadeCaixaPorHora } from './produtividadeDiaDiaGetDataDtoProdutividadeProcessoItemProdutividadeCaixaPorHora';
import type { ProdutividadeDiaDiaGetDataDtoProdutividadeProcessoItemMediaEnderecosPorDemanda } from './produtividadeDiaDiaGetDataDtoProdutividadeProcessoItemMediaEnderecosPorDemanda';

export type ProdutividadeDiaDiaGetDataDtoProdutividadeProcessoItem = {
  centerid: ProdutividadeDiaDiaGetDataDtoProdutividadeProcessoItemCenterid;
  processo: ProdutividadeDiaDiaGetDataDtoProdutividadeProcessoItemProcesso;
  turno: ProdutividadeDiaDiaGetDataDtoProdutividadeProcessoItemTurno;
  criadoem: ProdutividadeDiaDiaGetDataDtoProdutividadeProcessoItemCriadoem;
  periodoInicio: ProdutividadeDiaDiaGetDataDtoProdutividadeProcessoItemPeriodoInicio;
  periodoFim: ProdutividadeDiaDiaGetDataDtoProdutividadeProcessoItemPeriodoFim;
  totalTempoPausa: ProdutividadeDiaDiaGetDataDtoProdutividadeProcessoItemTotalTempoPausa;
  totalCaixas: ProdutividadeDiaDiaGetDataDtoProdutividadeProcessoItemTotalCaixas;
  tempoTotal: ProdutividadeDiaDiaGetDataDtoProdutividadeProcessoItemTempoTotal;
  totalDemandas: ProdutividadeDiaDiaGetDataDtoProdutividadeProcessoItemTotalDemandas;
  totalEnderecosVisitados: ProdutividadeDiaDiaGetDataDtoProdutividadeProcessoItemTotalEnderecosVisitados;
  tempoTrabalhado: ProdutividadeDiaDiaGetDataDtoProdutividadeProcessoItemTempoTrabalhado;
  produtividadeCaixaPorHora: ProdutividadeDiaDiaGetDataDtoProdutividadeProcessoItemProdutividadeCaixaPorHora;
  mediaEnderecosPorDemanda: ProdutividadeDiaDiaGetDataDtoProdutividadeProcessoItemMediaEnderecosPorDemanda;
};
