/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */
import type { ResponseRavexDtoNotasItemTipo } from './responseRavexDtoNotasItemTipo';
import type { ResponseRavexDtoNotasItemNotaFiscalParcial } from './responseRavexDtoNotasItemNotaFiscalParcial';
import type { ResponseRavexDtoNotasItemDescMotivoDevolucao } from './responseRavexDtoNotasItemDescMotivoDevolucao';
import type { ResponseRavexDtoNotasItemOperador } from './responseRavexDtoNotasItemOperador';
import type { ResponseRavexDtoNotasItemItensItem } from './responseRavexDtoNotasItemItensItem';

export type ResponseRavexDtoNotasItem = {
  tipo: ResponseRavexDtoNotasItemTipo;
  notaFiscal: string;
  notaFiscalParcial?: ResponseRavexDtoNotasItemNotaFiscalParcial;
  motivoDevolucao: string;
  descMotivoDevolucao: ResponseRavexDtoNotasItemDescMotivoDevolucao;
  operador?: ResponseRavexDtoNotasItemOperador;
  empresa: string;
  itens: ResponseRavexDtoNotasItemItensItem[];
};
