/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */

export type ResponseRavexDtoNotasItemTipo = typeof ResponseRavexDtoNotasItemTipo[keyof typeof ResponseRavexDtoNotasItemTipo];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ResponseRavexDtoNotasItemTipo = {
  DEVOLUCAO: 'DEVOLUCAO',
  DEVOLUCAO_PARCIAL: 'DEVOLUCAO_PARCIAL',
  REENTREGA: 'REENTREGA',
} as const;
