/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */
import type { ResultadoDemandaDtoNotasItem } from './resultadoDemandaDtoNotasItem';
import type { ResultadoDemandaDtoItensItem } from './resultadoDemandaDtoItensItem';

export interface ResultadoDemandaDto {
  demandaId: number;
  placa: string;
  motorista: string;
  transportadora: string;
  doca: string;
  criadoPor: string;
  conferente: string;
  criadoEm: string;
  LiberadoParaConferenciaEm: string;
  InicioConferenciaEm: string;
  FimConferenciaEm: string;
  FinalizadoEm: string;
  Status: string;
  FechouComAnomalia: boolean;
  notas: ResultadoDemandaDtoNotasItem[];
  itens: ResultadoDemandaDtoItensItem[];
}
