/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */
import type { ResultTransporteDtoOutputStatus } from './resultTransporteDtoOutputStatus';
import type { ResultTransporteDtoOutputObs } from './resultTransporteDtoOutputObs';
import type { ResultTransporteDtoOutputCarregamento } from './resultTransporteDtoOutputCarregamento';
import type { ResultTransporteDtoOutputConferencia } from './resultTransporteDtoOutputConferencia';
import type { ResultTransporteDtoOutputSeparacao } from './resultTransporteDtoOutputSeparacao';

export interface ResultTransporteDtoOutput {
  numeroTransporte: string;
  status: ResultTransporteDtoOutputStatus;
  /** @minLength 1 */
  nomeRota: string;
  /** @minLength 1 */
  nomeTransportadora: string;
  /** @minLength 1 */
  placa: string;
  /** @minLength 1 */
  criadoEm: string;
  /** @minLength 1 */
  atualizadoEm: string;
  /** @minLength 1 */
  cadastradoPorId: string;
  /** @minLength 1 */
  dataExpedicao: string;
  /** @minLength 1 */
  centerId: string;
  obs: ResultTransporteDtoOutputObs;
  prioridade?: number;
  cargaParada?: boolean;
  carregamento?: ResultTransporteDtoOutputCarregamento;
  conferencia?: ResultTransporteDtoOutputConferencia;
  separacao?: ResultTransporteDtoOutputSeparacao;
  qtdImpressoes?: number;
}
