/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */
import type { ReturnInfoGeralRavexNotasItemTipo } from './returnInfoGeralRavexNotasItemTipo';
import type { ReturnInfoGeralRavexNotasItemNotaFiscalParcial } from './returnInfoGeralRavexNotasItemNotaFiscalParcial';
import type { ReturnInfoGeralRavexNotasItemDescMotivoDevolucao } from './returnInfoGeralRavexNotasItemDescMotivoDevolucao';
import type { ReturnInfoGeralRavexNotasItemOperador } from './returnInfoGeralRavexNotasItemOperador';
import type { ReturnInfoGeralRavexNotasItemItensItem } from './returnInfoGeralRavexNotasItemItensItem';

export type ReturnInfoGeralRavexNotasItem = {
  tipo: ReturnInfoGeralRavexNotasItemTipo;
  notaFiscal: string;
  notaFiscalParcial?: ReturnInfoGeralRavexNotasItemNotaFiscalParcial;
  motivoDevolucao: string;
  descMotivoDevolucao: ReturnInfoGeralRavexNotasItemDescMotivoDevolucao;
  operador?: ReturnInfoGeralRavexNotasItemOperador;
  empresa: string;
  itens: ReturnInfoGeralRavexNotasItemItensItem[];
};
