/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */
import type { TransporteComRelacionamentosGetDtoPaletesItemTipoProcesso } from './transporteComRelacionamentosGetDtoPaletesItemTipoProcesso';
import type { TransporteComRelacionamentosGetDtoPaletesItemDemandaId } from './transporteComRelacionamentosGetDtoPaletesItemDemandaId';
import type { TransporteComRelacionamentosGetDtoPaletesItemStatus } from './transporteComRelacionamentosGetDtoPaletesItemStatus';
import type { TransporteComRelacionamentosGetDtoPaletesItemFim } from './transporteComRelacionamentosGetDtoPaletesItemFim';
import type { TransporteComRelacionamentosGetDtoPaletesItemInicio } from './transporteComRelacionamentosGetDtoPaletesItemInicio';

export type TransporteComRelacionamentosGetDtoPaletesItem = {
  id: string;
  empresa: string;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  quantidadeCaixas: number;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  quantidadeUnidades: number;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  quantidadePaletes: number;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  enderecoVisitado: number;
  segmento: string;
  transporteId: string;
  tipoProcesso: TransporteComRelacionamentosGetDtoPaletesItemTipoProcesso;
  criadoEm: string;
  atualizadoEm: string;
  demandaId: TransporteComRelacionamentosGetDtoPaletesItemDemandaId;
  status: TransporteComRelacionamentosGetDtoPaletesItemStatus;
  validado: boolean;
  criadoPorId: string;
  fim: TransporteComRelacionamentosGetDtoPaletesItemFim;
  inicio: TransporteComRelacionamentosGetDtoPaletesItemInicio;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  totalCaixas: number;
  /**
   * @minimum -140737488355328
   * @maximum 140737488355327
   */
  pesoLiquido: number;
  dataTransporte?: string;
};
