/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */
import type { TransporteComRelacionamentosGetDtoStatus } from './transporteComRelacionamentosGetDtoStatus';
import type { TransporteComRelacionamentosGetDtoObs } from './transporteComRelacionamentosGetDtoObs';
import type { TransporteComRelacionamentosGetDtoCarregamento } from './transporteComRelacionamentosGetDtoCarregamento';
import type { TransporteComRelacionamentosGetDtoConferencia } from './transporteComRelacionamentosGetDtoConferencia';
import type { TransporteComRelacionamentosGetDtoSeparacao } from './transporteComRelacionamentosGetDtoSeparacao';
import type { TransporteComRelacionamentosGetDtoCargaParada } from './transporteComRelacionamentosGetDtoCargaParada';
import type { TransporteComRelacionamentosGetDtoPaletesItem } from './transporteComRelacionamentosGetDtoPaletesItem';
import type { TransporteComRelacionamentosGetDtoCortesItem } from './transporteComRelacionamentosGetDtoCortesItem';
import type { TransporteComRelacionamentosGetDtoHistoricoTransporteItem } from './transporteComRelacionamentosGetDtoHistoricoTransporteItem';
import type { TransporteComRelacionamentosGetDtoImpressaoMapaItem } from './transporteComRelacionamentosGetDtoImpressaoMapaItem';
import type { TransporteComRelacionamentosGetDtoClientesItem } from './transporteComRelacionamentosGetDtoClientesItem';

export interface TransporteComRelacionamentosGetDto {
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  id: number;
  numeroTransporte: string;
  status: TransporteComRelacionamentosGetDtoStatus;
  nomeRota: string;
  nomeTransportadora: string;
  placa: string;
  criadoEm: string;
  atualizadoEm: string;
  cadastradoPorId: string;
  dataExpedicao: string;
  centerId: string;
  obs: TransporteComRelacionamentosGetDtoObs;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  prioridade: number;
  carregamento: TransporteComRelacionamentosGetDtoCarregamento;
  conferencia: TransporteComRelacionamentosGetDtoConferencia;
  separacao: TransporteComRelacionamentosGetDtoSeparacao;
  cargaParada: TransporteComRelacionamentosGetDtoCargaParada;
  paletes?: TransporteComRelacionamentosGetDtoPaletesItem[];
  cortes?: TransporteComRelacionamentosGetDtoCortesItem[];
  historicoTransporte?: TransporteComRelacionamentosGetDtoHistoricoTransporteItem[];
  impressaoMapa?: TransporteComRelacionamentosGetDtoImpressaoMapaItem[];
  clientes?: TransporteComRelacionamentosGetDtoClientesItem[];
}
