/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */
import type { UpdateMovimentacaoDtoIdUsuario } from './updateMovimentacaoDtoIdUsuario';
import type { UpdateMovimentacaoDtoOrigem } from './updateMovimentacaoDtoOrigem';
import type { UpdateMovimentacaoDtoDestino } from './updateMovimentacaoDtoDestino';
import type { UpdateMovimentacaoDtoStatus } from './updateMovimentacaoDtoStatus';
import type { UpdateMovimentacaoDtoDataCriacao } from './updateMovimentacaoDtoDataCriacao';
import type { UpdateMovimentacaoDtoDataExecucao } from './updateMovimentacaoDtoDataExecucao';
import type { UpdateMovimentacaoDtoSku } from './updateMovimentacaoDtoSku';
import type { UpdateMovimentacaoDtoDescricao } from './updateMovimentacaoDtoDescricao';
import type { UpdateMovimentacaoDtoLote } from './updateMovimentacaoDtoLote';
import type { UpdateMovimentacaoDtoExecutadoPor } from './updateMovimentacaoDtoExecutadoPor';
import type { UpdateMovimentacaoDtoIniciado } from './updateMovimentacaoDtoIniciado';

export interface UpdateMovimentacaoDto {
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  idMov?: number;
  idUsuario?: UpdateMovimentacaoDtoIdUsuario;
  idCentro?: string;
  /** @maxLength 50 */
  palete?: string;
  origem?: UpdateMovimentacaoDtoOrigem;
  destino?: UpdateMovimentacaoDtoDestino;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  prioridade?: number;
  status?: UpdateMovimentacaoDtoStatus;
  dataCriacao?: UpdateMovimentacaoDtoDataCriacao;
  dataExecucao?: UpdateMovimentacaoDtoDataExecucao;
  sku?: UpdateMovimentacaoDtoSku;
  descricao?: UpdateMovimentacaoDtoDescricao;
  lote?: UpdateMovimentacaoDtoLote;
  executadoPor?: UpdateMovimentacaoDtoExecutadoPor;
  iniciado?: UpdateMovimentacaoDtoIniciado;
}
