/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */
import * as zod from 'zod';


/**
 * @summary Login
 */
export const loginBodyPasswordMin = 6;

export const loginBody = zod.object({
  "id": zod.string(),
  "password": zod.string().min(loginBodyPasswordMin)
})

export const loginResponse = zod.string()

