/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */
import * as zod from 'zod';


/**
 * @summary Criar um novo produto
 */
export const createProdutoBody = zod.object({
  "codDum": zod.string().describe('Código DUM do produto'),
  "codEan": zod.string().describe('Código EAN do produto'),
  "sku": zod.string().describe('SKU do produto'),
  "descricao": zod.string().describe('Descrição do produto'),
  "shelf": zod.number().describe('Shelf do produto'),
  "pesoLiquidoCaixa": zod.string().describe('Peso líquido da caixa'),
  "pesoLiquidoUnidade": zod.string().describe('Peso líquido da unidade'),
  "unPorCaixa": zod.number().describe('Unidades por caixa'),
  "caixaPorPallet": zod.number().describe('Caixas por pallet'),
  "segmento": zod.string().describe('Segmento do produto'),
  "empresa": zod.string().describe('Empresa do produto'),
  "criadoEm": zod.string().describe('Criado em')
})

/**
 * @summary Buscar todos os produtos
 */
export const findAllProdutosResponseItem = zod.object({
  "codDum": zod.string().describe('Código DUM do produto'),
  "codEan": zod.string().describe('Código EAN do produto'),
  "sku": zod.string().describe('SKU do produto'),
  "descricao": zod.string().describe('Descrição do produto'),
  "shelf": zod.number().describe('Shelf do produto'),
  "pesoLiquidoCaixa": zod.string().describe('Peso líquido da caixa'),
  "pesoLiquidoUnidade": zod.string().describe('Peso líquido da unidade'),
  "unPorCaixa": zod.number().describe('Unidades por caixa'),
  "caixaPorPallet": zod.number().describe('Caixas por pallet'),
  "segmento": zod.string().describe('Segmento do produto'),
  "empresa": zod.string().describe('Empresa do produto'),
  "criadoEm": zod.string().describe('Criado em')
})
export const findAllProdutosResponse = zod.array(findAllProdutosResponseItem)

/**
 * @summary Criar múltiplos produtos
 */
export const createManyProdutosBodyItem = zod.object({
  "codDum": zod.string().describe('Código DUM do produto'),
  "codEan": zod.string().describe('Código EAN do produto'),
  "sku": zod.string().describe('SKU do produto'),
  "descricao": zod.string().describe('Descrição do produto'),
  "shelf": zod.number().describe('Shelf do produto'),
  "pesoLiquidoCaixa": zod.string().describe('Peso líquido da caixa'),
  "pesoLiquidoUnidade": zod.string().describe('Peso líquido da unidade'),
  "unPorCaixa": zod.number().describe('Unidades por caixa'),
  "caixaPorPallet": zod.number().describe('Caixas por pallet'),
  "segmento": zod.string().describe('Segmento do produto'),
  "empresa": zod.string().describe('Empresa do produto'),
  "criadoEm": zod.string().describe('Criado em')
})
export const createManyProdutosBody = zod.array(createManyProdutosBodyItem)

/**
 * @summary Buscar um produto pelo SKU
 */
export const findProdutoBySkuParams = zod.object({
  "sku": zod.string()
})

/**
 * @summary Atualizar um produto pelo SKU
 */
export const updateProdutoBySkuParams = zod.object({
  "sku": zod.string()
})

export const updateProdutoBySkuBody = zod.object({
  "codDum": zod.string().optional().describe('Código DUM do produto'),
  "codEan": zod.string().optional().describe('Código EAN do produto'),
  "sku": zod.string().optional().describe('SKU do produto'),
  "descricao": zod.string().optional().describe('Descrição do produto'),
  "shelf": zod.number().optional().describe('Shelf do produto'),
  "pesoLiquidoCaixa": zod.string().optional().describe('Peso líquido da caixa'),
  "pesoLiquidoUnidade": zod.string().optional().describe('Peso líquido da unidade'),
  "unPorCaixa": zod.number().optional().describe('Unidades por caixa'),
  "caixaPorPallet": zod.number().optional().describe('Caixas por pallet'),
  "segmento": zod.string().optional().describe('Segmento do produto'),
  "empresa": zod.string().optional().describe('Empresa do produto'),
  "criadoEm": zod.string().optional().describe('Criado em')
})

/**
 * @summary Deletar um produto pelo SKU
 */
export const deleteProdutoBySkuParams = zod.object({
  "sku": zod.string()
})

