/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */
import * as zod from 'zod';


/**
 * @summary Buscar todos os produtos
 */
export const findAllProdutosResponseShelfMax = 9007199254740991;export const findAllProdutosResponseUnPorCaixaMax = 9007199254740991;export const findAllProdutosResponseCaixaPorPalletMax = 9007199254740991;

export const findAllProdutosResponseItem = zod.object({
  "codDum": zod.string().optional(),
  "codEan": zod.string().optional(),
  "sku": zod.string().min(1),
  "descricao": zod.string().min(1),
  "shelf": zod.number().max(findAllProdutosResponseShelfMax),
  "tipoPeso": zod.enum(['PVAR', 'PPAR']),
  "pesoLiquidoCaixa": zod.string().min(1),
  "pesoLiquidoUnidade": zod.string().min(1),
  "unPorCaixa": zod.number().max(findAllProdutosResponseUnPorCaixaMax),
  "caixaPorPallet": zod.number().max(findAllProdutosResponseCaixaPorPalletMax),
  "segmento": zod.enum(['SECO', 'REFR']),
  "empresa": zod.enum(['ITB', 'LDB', 'DPA']),
  "criadoEm": zod.string().optional()
})
export const findAllProdutosResponse = zod.array(findAllProdutosResponseItem)

