/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */
import * as zod from 'zod';


/**
 * @summary Buscar resultado de demanda de devolução
 */
export const getResultadoDemandaDevolucaoParams = zod.object({
  "id": zod.string()
})

export const getResultadoDemandaDevolucaoResponse = zod.object({
  "demandaId": zod.number(),
  "placa": zod.string(),
  "motorista": zod.string(),
  "transportadora": zod.string(),
  "doca": zod.string(),
  "criadoPor": zod.string(),
  "conferente": zod.string(),
  "criadoEm": zod.string(),
  "LiberadoParaConferenciaEm": zod.string(),
  "InicioConferenciaEm": zod.string(),
  "FimConferenciaEm": zod.string(),
  "FinalizadoEm": zod.string(),
  "Status": zod.string(),
  "FechouComAnomalia": zod.boolean(),
  "notas": zod.array(zod.object({
  "notaFiscal": zod.string(),
  "notaFiscalParcial": zod.string(),
  "descMotivoDevolucao": zod.string(),
  "viagemId": zod.string(),
  "tipo": zod.enum(['DEVOLUCAO', 'DEVOLUCAO_PARCIAL', 'REENTREGA'])
})),
  "itens": zod.array(zod.object({
  "sku": zod.string(),
  "descricao": zod.string(),
  "quantidadeCaixasContabil": zod.number(),
  "quantidadeUnidadesContabil": zod.number(),
  "quantidadeCaixasFisico": zod.number(),
  "quantidadeUnidadesFisico": zod.number(),
  "saldoCaixas": zod.number(),
  "saldoUnidades": zod.number(),
  "avariaCaixas": zod.number(),
  "avariaUnidades": zod.number()
}))
})

/**
 * Busca informações completas de uma viagem pelo ID, incluindo dados do motorista, veículo, transportadora, notas fiscais e itens associados com produtos mapeados.
 * @summary Buscar informações da viagem
 */
export const getInfoByViagemIdParams = zod.object({
  "viagemId": zod.string()
})

export const getInfoByViagemIdResponsePlacaMin = 7;
export const getInfoByViagemIdResponsePlacaMax = 7;export const getInfoByViagemIdResponseNotasItemItensItemDescricaoRegExp = new RegExp('^(?!produto não encontrado$).*$');


export const getInfoByViagemIdResponse = zod.object({
  "idViagem": zod.string(),
  "placa": zod.string().min(getInfoByViagemIdResponsePlacaMin).max(getInfoByViagemIdResponsePlacaMax),
  "motorista": zod.string(),
  "transportadora": zod.string(),
  "notas": zod.array(zod.object({
  "tipo": zod.enum(['DEVOLUCAO', 'DEVOLUCAO_PARCIAL', 'REENTREGA']),
  "notaFiscal": zod.string(),
  "notaFiscalParcial": zod.union([zod.string(),zod.null()]).optional(),
  "motivoDevolucao": zod.string(),
  "descMotivoDevolucao": zod.union([zod.string(),zod.null()]),
  "operador": zod.union([zod.string(),zod.null()]).optional(),
  "empresa": zod.string(),
  "itens": zod.array(zod.object({
  "sku": zod.string(),
  "descricao": zod.string().regex(getInfoByViagemIdResponseNotasItemItensItemDescricaoRegExp),
  "pesoLiquido": zod.number(),
  "quantidadeRavex": zod.number(),
  "quantidadeCaixas": zod.number(),
  "quantidadeUnidades": zod.number(),
  "fatorConversao": zod.number(),
  "unPorCaixa": zod.number(),
  "decimal": zod.number()
}))
}))
})

/**
 * @summary Adicionar demanda
 */
export const addDemandaDevolucaoParams = zod.object({
  "centerId": zod.string()
})

export const addDemandaDevolucaoBodyCargaSegregadaDefault = false;export const addDemandaDevolucaoBodyQuantidadePaletesDefaultOne = 0;
export const addDemandaDevolucaoBodyQuantidadePaletesMinOne = 0;
export const addDemandaDevolucaoBodyQuantidadePaletesMaxOne = 9007199254740991;

export const addDemandaDevolucaoBody = zod.object({
  "placa": zod.string().min(1),
  "motorista": zod.string().min(1),
  "idTransportadora": zod.union([zod.string(),zod.null()]).optional(),
  "telefone": zod.union([zod.string(),zod.null()]).optional(),
  "cargaSegregada": zod.boolean().optional(),
  "quantidadePaletes": zod.union([zod.number().min(addDemandaDevolucaoBodyQuantidadePaletesMinOne).max(addDemandaDevolucaoBodyQuantidadePaletesMaxOne),zod.null()]).optional(),
  "doca": zod.union([zod.string(),zod.null()]).optional(),
  "centerId": zod.string().min(1),
  "adicionadoPorId": zod.string().min(1),
  "conferenteId": zod.union([zod.string(),zod.null()]).optional(),
  "senha": zod.string().min(1),
  "viagemId": zod.union([zod.string(),zod.null()]).optional(),
  "status": zod.enum(['AGUARDANDO_LIBERACAO', 'AGUARDANDO_CONFERENCIA', 'EM_CONFERENCIA', 'CONFERENCIA_FINALIZADA', 'FINALIZADO', 'CANCELADO']),
  "criadoEm": zod.string(),
  "id": zod.number()
})

export const addDemandaDevolucaoResponse = zod.string()

/**
 * @summary Listar demandas de devolução
 */
export const listarDemandasDevolucaoParams = zod.object({
  "centerId": zod.string(),
  "data": zod.string()
})

export const listarDemandasDevolucaoResponseCargaSegregadaDefault = false;export const listarDemandasDevolucaoResponseQuantidadePaletesDefaultOne = 0;
export const listarDemandasDevolucaoResponseQuantidadePaletesMinOne = 0;
export const listarDemandasDevolucaoResponseQuantidadePaletesMaxOne = 9007199254740991;

export const listarDemandasDevolucaoResponseItem = zod.object({
  "placa": zod.string().min(1),
  "motorista": zod.string().min(1),
  "idTransportadora": zod.union([zod.string(),zod.null()]).optional(),
  "telefone": zod.union([zod.string(),zod.null()]).optional(),
  "cargaSegregada": zod.boolean().optional(),
  "quantidadePaletes": zod.union([zod.number().min(listarDemandasDevolucaoResponseQuantidadePaletesMinOne).max(listarDemandasDevolucaoResponseQuantidadePaletesMaxOne),zod.null()]).optional(),
  "doca": zod.union([zod.string(),zod.null()]).optional(),
  "centerId": zod.string().min(1),
  "adicionadoPorId": zod.string().min(1),
  "conferenteId": zod.union([zod.string(),zod.null()]).optional(),
  "senha": zod.string().min(1),
  "viagemId": zod.union([zod.string(),zod.null()]).optional(),
  "status": zod.enum(['AGUARDANDO_LIBERACAO', 'AGUARDANDO_CONFERENCIA', 'EM_CONFERENCIA', 'CONFERENCIA_FINALIZADA', 'FINALIZADO', 'CANCELADO']),
  "criadoEm": zod.string(),
  "id": zod.number()
})
export const listarDemandasDevolucaoResponse = zod.array(listarDemandasDevolucaoResponseItem)

/**
 * @summary Buscar demanda de devolução por ID
 */
export const getDemandaByIdDevolucaoParams = zod.object({
  "id": zod.string()
})

export const getDemandaByIdDevolucaoResponseCargaSegregadaDefault = false;export const getDemandaByIdDevolucaoResponseQuantidadePaletesDefaultOne = 0;
export const getDemandaByIdDevolucaoResponseQuantidadePaletesMinOne = 0;
export const getDemandaByIdDevolucaoResponseQuantidadePaletesMaxOne = 9007199254740991;

export const getDemandaByIdDevolucaoResponse = zod.object({
  "placa": zod.string().min(1),
  "motorista": zod.string().min(1),
  "idTransportadora": zod.union([zod.string(),zod.null()]).optional(),
  "telefone": zod.union([zod.string(),zod.null()]).optional(),
  "cargaSegregada": zod.boolean().optional(),
  "quantidadePaletes": zod.union([zod.number().min(getDemandaByIdDevolucaoResponseQuantidadePaletesMinOne).max(getDemandaByIdDevolucaoResponseQuantidadePaletesMaxOne),zod.null()]).optional(),
  "doca": zod.union([zod.string(),zod.null()]).optional(),
  "centerId": zod.string().min(1),
  "adicionadoPorId": zod.string().min(1),
  "conferenteId": zod.union([zod.string(),zod.null()]).optional(),
  "senha": zod.string().min(1),
  "viagemId": zod.union([zod.string(),zod.null()]).optional(),
  "status": zod.enum(['AGUARDANDO_LIBERACAO', 'AGUARDANDO_CONFERENCIA', 'EM_CONFERENCIA', 'CONFERENCIA_FINALIZADA', 'FINALIZADO', 'CANCELADO']),
  "criadoEm": zod.string(),
  "id": zod.number()
})

/**
 * @summary Adicionar nota de devolução
 */
export const addNotaDevolucaoBody = zod.object({
  "empresa": zod.enum(['ITB', 'LDB', 'DPA']),
  "devolucaoDemandaId": zod.number(),
  "notaFiscal": zod.string(),
  "motivoDevolucao": zod.string(),
  "descMotivoDevolucao": zod.string(),
  "nfParcial": zod.string().optional(),
  "idViagemRavex": zod.string().optional(),
  "tipo": zod.enum(['DEVOLUCAO', 'DEVOLUCAO_PARCIAL', 'REENTREGA']),
  "itens": zod.array(zod.object({
  "sku": zod.string(),
  "descricao": zod.string(),
  "lote": zod.string().optional(),
  "fabricacao": zod.number().optional(),
  "sif": zod.string().optional(),
  "quantidadeCaixas": zod.number(),
  "quantidadeUnidades": zod.number(),
  "avariaCaixas": zod.number().optional(),
  "tipo": zod.enum(['DEVOLUCAO', 'DEVOLUCAO_PARCIAL', 'REENTREGA']),
  "demandaId": zod.number()
}))
})

export const addNotaDevolucaoResponse = zod.string()

/**
 * @summary Liberar demanda para conferência
 */
export const liberarDemandaDevolucaoParams = zod.object({
  "demandaId": zod.string()
})

export const liberarDemandaDevolucaoResponse = zod.string()

/**
 * @summary Listar demandas em aberto
 */
export const listarDemandasEmAbertoDevolucaoMobileParams = zod.object({
  "centerId": zod.string()
})

export const listarDemandasEmAbertoDevolucaoMobileResponseCargaSegregadaDefault = false;export const listarDemandasEmAbertoDevolucaoMobileResponseQuantidadePaletesDefaultOne = 0;
export const listarDemandasEmAbertoDevolucaoMobileResponseQuantidadePaletesMinOne = 0;
export const listarDemandasEmAbertoDevolucaoMobileResponseQuantidadePaletesMaxOne = 9007199254740991;

export const listarDemandasEmAbertoDevolucaoMobileResponseItem = zod.object({
  "placa": zod.string().min(1),
  "motorista": zod.string().min(1),
  "idTransportadora": zod.union([zod.string(),zod.null()]).optional(),
  "telefone": zod.union([zod.string(),zod.null()]).optional(),
  "cargaSegregada": zod.boolean().optional(),
  "quantidadePaletes": zod.union([zod.number().min(listarDemandasEmAbertoDevolucaoMobileResponseQuantidadePaletesMinOne).max(listarDemandasEmAbertoDevolucaoMobileResponseQuantidadePaletesMaxOne),zod.null()]).optional(),
  "doca": zod.union([zod.string(),zod.null()]).optional(),
  "centerId": zod.string().min(1),
  "adicionadoPorId": zod.string().min(1),
  "conferenteId": zod.union([zod.string(),zod.null()]).optional(),
  "senha": zod.string().min(1),
  "viagemId": zod.union([zod.string(),zod.null()]).optional(),
  "status": zod.enum(['AGUARDANDO_LIBERACAO', 'AGUARDANDO_CONFERENCIA', 'EM_CONFERENCIA', 'CONFERENCIA_FINALIZADA', 'FINALIZADO', 'CANCELADO']),
  "criadoEm": zod.string(),
  "id": zod.number()
})
export const listarDemandasEmAbertoDevolucaoMobileResponse = zod.array(listarDemandasEmAbertoDevolucaoMobileResponseItem)

/**
 * @summary Iniciar conferência
 */
export const startDemandaDevolucaoMobileParams = zod.object({
  "demandaId": zod.string(),
  "doca": zod.string()
})

export const startDemandaDevolucaoMobileResponse = zod.string()

/**
 * @summary Listar itens contabilizados
 */
export const getItensContabilDevolucaoMobileParams = zod.object({
  "demandaId": zod.string()
})

export const getItensContabilDevolucaoMobileResponseItem = zod.object({
  "demandaId": zod.number(),
  "sku": zod.string(),
  "descricao": zod.string(),
  "tipo": zod.enum(['CONTABIL', 'FISICO']),
  "tipoDevolucao": zod.enum(['RETORNO', 'REENTREGA']),
  "quantidadeCaixas": zod.number(),
  "quantidadeUnidades": zod.number(),
  "avariaCaixas": zod.number(),
  "avariaUnidades": zod.number()
})
export const getItensContabilDevolucaoMobileResponse = zod.array(getItensContabilDevolucaoMobileResponseItem)

/**
 * @summary Adicionar check list
 */
export const addCheckListDevolucaoMobileParams = zod.object({
  "demandaId": zod.string()
})

export const addCheckListDevolucaoMobileBodyTemperaturaBauRegExp = new RegExp('^-?\\d+(\\.\\d+)?$');
export const addCheckListDevolucaoMobileBodyTemperaturaProdutoRegExp = new RegExp('^-?\\d+(\\.\\d+)?$');


export const addCheckListDevolucaoMobileBody = zod.object({
  "demandaId": zod.string().min(1),
  "temperaturaBau": zod.string().regex(addCheckListDevolucaoMobileBodyTemperaturaBauRegExp),
  "temperaturaProduto": zod.string().regex(addCheckListDevolucaoMobileBodyTemperaturaProdutoRegExp),
  "anomalias": zod.string().optional()
})

/**
 * @summary Iniciar conferência
 */
export const addContagemCegaParams = zod.object({
  "demandaId": zod.string()
})

export const addContagemCegaBodyQuantidadeCaixasDefault = 0;export const addContagemCegaBodyQuantidadeUnidadesDefault = 0;

export const addContagemCegaBodyItem = zod.object({
  "descricao": zod.string(),
  "sku": zod.string(),
  "uuid": zod.union([zod.string(),zod.null()]).optional(),
  "quantidadeCaixas": zod.number().optional(),
  "quantidadeUnidades": zod.number().optional(),
  "lote": zod.string()
})
export const addContagemCegaBody = zod.array(addContagemCegaBodyItem)

/**
 * @summary Finalizar demanda
 */
export const finalizarDemandaDevolucaoMobileParams = zod.object({
  "demandaId": zod.string()
})

/**
 * @summary Adicionar anomalia de devolução
 */
export const addAnomaliaDevolucaoBody = zod.object({
  "demandaId": zod.number(),
  "uuid": zod.string(),
  "sku": zod.string(),
  "descricao": zod.string(),
  "lote": zod.string(),
  "tipo": zod.string(),
  "natureza": zod.string(),
  "causa": zod.string(),
  "tratado": zod.boolean().optional(),
  "quantidadeCaixas": zod.number(),
  "quantidadeUnidades": zod.number(),
  "imagens": zod.array(zod.string())
})

/**
 * @summary Gerar URL pré-assinada para upload de check list
 */
export const getPresignedUrlCheckListDevolucaoParams = zod.object({
  "filename": zod.string()
})

export const getPresignedUrlCheckListDevolucaoResponse = zod.string()

/**
 * @summary Gerar URL pré-assinada para upload de anomalia
 */
export const getPresignedUrlAnomaliaDevolucaoParams = zod.object({
  "filename": zod.string()
})

export const getPresignedUrlAnomaliaDevolucaoResponse = zod.string()

/**
 * @summary Gerar URL pré-assinada para upload de fim de devolução
 */
export const getPresignedUrlFimDevolucaoParams = zod.object({
  "filename": zod.string()
})

export const getPresignedUrlFimDevolucaoResponse = zod.string()

/**
 * @summary Adicionar imagem de fim de devolução
 */
export const addImagemFimDevolucaoParams = zod.object({
  "demandaId": zod.string()
})

export const addImagemFimDevolucaoBodyItem = zod.string()
export const addImagemFimDevolucaoBody = zod.array(addImagemFimDevolucaoBodyItem)

/**
 * @summary Listar itens da demanda
 */
export const getItensByDemandaIdDevolucaoMobileParams = zod.object({
  "demandaId": zod.string()
})

export const getItensByDemandaIdDevolucaoMobileResponseIdMin = -9007199254740991;
export const getItensByDemandaIdDevolucaoMobileResponseIdMax = 9007199254740991;export const getItensByDemandaIdDevolucaoMobileResponseQuantidadeCaixasMin = -9007199254740991;
export const getItensByDemandaIdDevolucaoMobileResponseQuantidadeCaixasMax = 9007199254740991;export const getItensByDemandaIdDevolucaoMobileResponseQuantidadeUnidadesMin = -9007199254740991;
export const getItensByDemandaIdDevolucaoMobileResponseQuantidadeUnidadesMax = 9007199254740991;export const getItensByDemandaIdDevolucaoMobileResponseDemandaIdMin = -9007199254740991;
export const getItensByDemandaIdDevolucaoMobileResponseDemandaIdMax = 9007199254740991;export const getItensByDemandaIdDevolucaoMobileResponseAvariaCaixasMin = -9007199254740991;
export const getItensByDemandaIdDevolucaoMobileResponseAvariaCaixasMax = 9007199254740991;export const getItensByDemandaIdDevolucaoMobileResponseAvariaUnidadesMin = -9007199254740991;
export const getItensByDemandaIdDevolucaoMobileResponseAvariaUnidadesMax = 9007199254740991;export const getItensByDemandaIdDevolucaoMobileResponseNotaIdMin = -9007199254740991;
export const getItensByDemandaIdDevolucaoMobileResponseNotaIdMax = 9007199254740991;

export const getItensByDemandaIdDevolucaoMobileResponseItem = zod.object({
  "id": zod.number().min(getItensByDemandaIdDevolucaoMobileResponseIdMin).max(getItensByDemandaIdDevolucaoMobileResponseIdMax).optional(),
  "sku": zod.string(),
  "descricao": zod.string(),
  "lote": zod.string().optional(),
  "fabricacao": zod.string().optional(),
  "sif": zod.string().optional(),
  "quantidadeCaixas": zod.number().min(getItensByDemandaIdDevolucaoMobileResponseQuantidadeCaixasMin).max(getItensByDemandaIdDevolucaoMobileResponseQuantidadeCaixasMax).optional(),
  "quantidadeUnidades": zod.number().min(getItensByDemandaIdDevolucaoMobileResponseQuantidadeUnidadesMin).max(getItensByDemandaIdDevolucaoMobileResponseQuantidadeUnidadesMax).optional(),
  "tipo": zod.enum(['CONTABIL', 'FISICO']),
  "tipoDevolucao": zod.enum(['RETORNO', 'REENTREGA']),
  "devolucaoNotasId": zod.string().optional(),
  "demandaId": zod.number().min(getItensByDemandaIdDevolucaoMobileResponseDemandaIdMin).max(getItensByDemandaIdDevolucaoMobileResponseDemandaIdMax),
  "avariaCaixas": zod.number().min(getItensByDemandaIdDevolucaoMobileResponseAvariaCaixasMin).max(getItensByDemandaIdDevolucaoMobileResponseAvariaCaixasMax).optional(),
  "avariaUnidades": zod.number().min(getItensByDemandaIdDevolucaoMobileResponseAvariaUnidadesMin).max(getItensByDemandaIdDevolucaoMobileResponseAvariaUnidadesMax).optional(),
  "nota_id": zod.number().min(getItensByDemandaIdDevolucaoMobileResponseNotaIdMin).max(getItensByDemandaIdDevolucaoMobileResponseNotaIdMax).optional()
})
export const getItensByDemandaIdDevolucaoMobileResponse = zod.array(getItensByDemandaIdDevolucaoMobileResponseItem)

/**
 * @summary Remover imagens do bucket
 */
export const removeImangesBucketParams = zod.object({
  "bucket": zod.string()
})

export const removeImangesBucketBodyItem = zod.string()
export const removeImangesBucketBody = zod.array(removeImangesBucketBodyItem)

/**
 * @summary Buscar anomalias por demanda
 */
export const getAnomaliasByDemandaParams = zod.object({
  "demandaId": zod.string()
})

export const getAnomaliasByDemandaResponseItem = zod.object({
  "id": zod.number(),
  "demandaId": zod.number(),
  "uuid": zod.union([zod.string(),zod.null()]).optional(),
  "sku": zod.string(),
  "lote": zod.string(),
  "tipo": zod.union([zod.string(),zod.null()]).optional(),
  "natureza": zod.union([zod.string(),zod.null()]).optional(),
  "causa": zod.union([zod.string(),zod.null()]).optional(),
  "descricao": zod.string(),
  "quantidadeCaixas": zod.number(),
  "quantidadeUnidades": zod.number(),
  "imagens": zod.array(zod.string())
})
export const getAnomaliasByDemandaResponse = zod.array(getAnomaliasByDemandaResponseItem)

/**
 * @summary Deletar anomalia de devolução
 */
export const deleteAnomaliaDevolucaoParams = zod.object({
  "anomaliaId": zod.string()
})

/**
 * @summary Iniciar conferência
 */
export const addContagemCegaIndividualParams = zod.object({
  "demandaId": zod.string()
})

export const addContagemCegaIndividualBodyQuantidadeCaixasDefault = 0;export const addContagemCegaIndividualBodyQuantidadeUnidadesDefault = 0;

export const addContagemCegaIndividualBody = zod.object({
  "descricao": zod.string(),
  "sku": zod.string(),
  "uuid": zod.union([zod.string(),zod.null()]).optional(),
  "quantidadeCaixas": zod.number().optional(),
  "quantidadeUnidades": zod.number().optional(),
  "lote": zod.string()
})

/**
 * @summary Deletar contagem cega
 */
export const deleteContagemCegaParams = zod.object({
  "uuid": zod.string()
})

/**
 * @summary Atualizar contagem cega
 */
export const updateContagemCegaParams = zod.object({
  "uuid": zod.string()
})

export const updateContagemCegaBodyQuantidadeCaixasDefault = 0;export const updateContagemCegaBodyQuantidadeUnidadesDefault = 0;

export const updateContagemCegaBody = zod.object({
  "descricao": zod.string(),
  "sku": zod.string(),
  "uuid": zod.union([zod.string(),zod.null()]).optional(),
  "quantidadeCaixas": zod.number().optional(),
  "quantidadeUnidades": zod.number().optional(),
  "lote": zod.string()
})

/**
 * @summary Adicionar imagens de check list
 */
export const addImangesCheckListParams = zod.object({
  "demandaId": zod.string(),
  "processo": zod.string()
})

export const addImangesCheckListBody = zod.object({
  "image": zod.string()
})

/**
 * @summary Adicionar imagem de anomalia
 */
export const addImagemAnomaliaParams = zod.object({
  "demandaId": zod.string()
})

export const addImagemAnomaliaBody = zod.object({
  "image": zod.string()
})

/**
 * @summary Buscar dados compactos de uma demanda de devolução
 */
export const getByDemandaCompactParams = zod.object({
  "id": zod.string()
})

export const getByDemandaCompactResponsePaletesEsperadasDefault = 0;
export const getByDemandaCompactResponsePaletesEsperadasMin = -9007199254740991;
export const getByDemandaCompactResponsePaletesEsperadasMax = 9007199254740991;export const getByDemandaCompactResponsePaletesReceptadasDefault = 0;
export const getByDemandaCompactResponsePaletesReceptadasMin = -9007199254740991;
export const getByDemandaCompactResponsePaletesReceptadasMax = 9007199254740991;export const getByDemandaCompactResponseItemsItemCaixasEsperadasDefault = 0;
export const getByDemandaCompactResponseItemsItemCaixasEsperadasMin = -9007199254740991;
export const getByDemandaCompactResponseItemsItemCaixasEsperadasMax = 9007199254740991;export const getByDemandaCompactResponseItemsItemUnidadesEsperadasDefault = 0;
export const getByDemandaCompactResponseItemsItemUnidadesEsperadasMin = -9007199254740991;
export const getByDemandaCompactResponseItemsItemUnidadesEsperadasMax = 9007199254740991;export const getByDemandaCompactResponseItemsItemIsReentregaDefault = false;export const getByDemandaCompactResponseItemsItemConferenciasItemCaixasDefault = 0;
export const getByDemandaCompactResponseItemsItemConferenciasItemCaixasMin = -9007199254740991;
export const getByDemandaCompactResponseItemsItemConferenciasItemCaixasMax = 9007199254740991;export const getByDemandaCompactResponseItemsItemConferenciasItemUnidadesDefault = 0;
export const getByDemandaCompactResponseItemsItemConferenciasItemUnidadesMin = -9007199254740991;
export const getByDemandaCompactResponseItemsItemConferenciasItemUnidadesMax = 9007199254740991;export const getByDemandaCompactResponseItemsItemAnomaliasItemCaixasDanificadasDefault = 0;
export const getByDemandaCompactResponseItemsItemAnomaliasItemCaixasDanificadasMin = -9007199254740991;
export const getByDemandaCompactResponseItemsItemAnomaliasItemCaixasDanificadasMax = 9007199254740991;export const getByDemandaCompactResponseItemsItemAnomaliasItemUnidadesDanificadasDefault = 0;
export const getByDemandaCompactResponseItemsItemAnomaliasItemUnidadesDanificadasMin = -9007199254740991;
export const getByDemandaCompactResponseItemsItemAnomaliasItemUnidadesDanificadasMax = 9007199254740991;

export const getByDemandaCompactResponse = zod.object({
  "id": zod.string(),
  "status": zod.enum(['open', 'in_conference', 'completed']),
  "paletesEsperadas": zod.number().min(getByDemandaCompactResponsePaletesEsperadasMin).max(getByDemandaCompactResponsePaletesEsperadasMax).optional(),
  "paletesReceptadas": zod.number().min(getByDemandaCompactResponsePaletesReceptadasMin).max(getByDemandaCompactResponsePaletesReceptadasMax).optional(),
  "doca": zod.union([zod.string(),zod.null()]).optional(),
  "dataGeracao": zod.string(),
  "responsavel": zod.union([zod.string(),zod.null()]).optional(),
  "placa": zod.string(),
  "docaRecepcao": zod.union([zod.string(),zod.null()]).optional(),
  "isSegregada": zod.union([zod.boolean(),zod.null()]).optional(),
  "checklist": zod.union([zod.object({
  "temperaturaTrunk": zod.union([zod.number(),zod.null()]).optional(),
  "temperaturaProduto": zod.union([zod.number(),zod.null()]).optional(),
  "observacoes": zod.union([zod.string(),zod.null()]).optional()
}),zod.null()]).optional(),
  "items": zod.array(zod.object({
  "id": zod.string(),
  "codigoProduto": zod.string(),
  "descricao": zod.string(),
  "caixasEsperadas": zod.number().min(getByDemandaCompactResponseItemsItemCaixasEsperadasMin).max(getByDemandaCompactResponseItemsItemCaixasEsperadasMax).optional(),
  "unidadesEsperadas": zod.number().min(getByDemandaCompactResponseItemsItemUnidadesEsperadasMin).max(getByDemandaCompactResponseItemsItemUnidadesEsperadasMax).optional(),
  "isReentrega": zod.boolean().optional(),
  "conferencias": zod.array(zod.object({
  "id": zod.string(),
  "codigoProduto": zod.string(),
  "lote": zod.union([zod.string(),zod.null()]).optional(),
  "caixas": zod.number().min(getByDemandaCompactResponseItemsItemConferenciasItemCaixasMin).max(getByDemandaCompactResponseItemsItemConferenciasItemCaixasMax).optional(),
  "unidades": zod.number().min(getByDemandaCompactResponseItemsItemConferenciasItemUnidadesMin).max(getByDemandaCompactResponseItemsItemConferenciasItemUnidadesMax).optional()
})),
  "anomalias": zod.array(zod.object({
  "id": zod.string(),
  "natureza": zod.union([zod.string(),zod.null()]).optional(),
  "tipo": zod.string(),
  "causa": zod.union([zod.string(),zod.null()]).optional(),
  "fotos": zod.array(zod.string()),
  "observacoes": zod.union([zod.string(),zod.null()]).optional(),
  "caixasDanificadas": zod.number().min(getByDemandaCompactResponseItemsItemAnomaliasItemCaixasDanificadasMin).max(getByDemandaCompactResponseItemsItemAnomaliasItemCaixasDanificadasMax).optional(),
  "unidadesDanificadas": zod.number().min(getByDemandaCompactResponseItemsItemAnomaliasItemUnidadesDanificadasMin).max(getByDemandaCompactResponseItemsItemAnomaliasItemUnidadesDanificadasMax).optional(),
  "lote": zod.string()
})),
  "extra": zod.boolean().optional()
})),
  "sync": zod.enum(['sync', 'pending', 'error', 'not_sync'])
})

/**
 * @summary Sincroniza e finaliza os dados de uma demanda de devolução
 */
export const finalizarDemandaCompactaParams = zod.object({
  "id": zod.string()
})

export const finalizarDemandaCompactaBodyPaletesEsperadasDefault = 0;
export const finalizarDemandaCompactaBodyPaletesEsperadasMin = -9007199254740991;
export const finalizarDemandaCompactaBodyPaletesEsperadasMax = 9007199254740991;export const finalizarDemandaCompactaBodyPaletesReceptadasDefault = 0;
export const finalizarDemandaCompactaBodyPaletesReceptadasMin = -9007199254740991;
export const finalizarDemandaCompactaBodyPaletesReceptadasMax = 9007199254740991;export const finalizarDemandaCompactaBodyItemsItemCaixasEsperadasDefault = 0;
export const finalizarDemandaCompactaBodyItemsItemCaixasEsperadasMin = -9007199254740991;
export const finalizarDemandaCompactaBodyItemsItemCaixasEsperadasMax = 9007199254740991;export const finalizarDemandaCompactaBodyItemsItemUnidadesEsperadasDefault = 0;
export const finalizarDemandaCompactaBodyItemsItemUnidadesEsperadasMin = -9007199254740991;
export const finalizarDemandaCompactaBodyItemsItemUnidadesEsperadasMax = 9007199254740991;export const finalizarDemandaCompactaBodyItemsItemIsReentregaDefault = false;export const finalizarDemandaCompactaBodyItemsItemConferenciasItemCaixasDefault = 0;
export const finalizarDemandaCompactaBodyItemsItemConferenciasItemCaixasMin = -9007199254740991;
export const finalizarDemandaCompactaBodyItemsItemConferenciasItemCaixasMax = 9007199254740991;export const finalizarDemandaCompactaBodyItemsItemConferenciasItemUnidadesDefault = 0;
export const finalizarDemandaCompactaBodyItemsItemConferenciasItemUnidadesMin = -9007199254740991;
export const finalizarDemandaCompactaBodyItemsItemConferenciasItemUnidadesMax = 9007199254740991;export const finalizarDemandaCompactaBodyItemsItemAnomaliasItemCaixasDanificadasDefault = 0;
export const finalizarDemandaCompactaBodyItemsItemAnomaliasItemCaixasDanificadasMin = -9007199254740991;
export const finalizarDemandaCompactaBodyItemsItemAnomaliasItemCaixasDanificadasMax = 9007199254740991;export const finalizarDemandaCompactaBodyItemsItemAnomaliasItemUnidadesDanificadasDefault = 0;
export const finalizarDemandaCompactaBodyItemsItemAnomaliasItemUnidadesDanificadasMin = -9007199254740991;
export const finalizarDemandaCompactaBodyItemsItemAnomaliasItemUnidadesDanificadasMax = 9007199254740991;

export const finalizarDemandaCompactaBody = zod.object({
  "id": zod.string(),
  "status": zod.enum(['open', 'in_conference', 'completed']),
  "paletesEsperadas": zod.number().min(finalizarDemandaCompactaBodyPaletesEsperadasMin).max(finalizarDemandaCompactaBodyPaletesEsperadasMax).optional(),
  "paletesReceptadas": zod.number().min(finalizarDemandaCompactaBodyPaletesReceptadasMin).max(finalizarDemandaCompactaBodyPaletesReceptadasMax).optional(),
  "doca": zod.union([zod.string(),zod.null()]).optional(),
  "dataGeracao": zod.string(),
  "responsavel": zod.union([zod.string(),zod.null()]).optional(),
  "placa": zod.string(),
  "docaRecepcao": zod.union([zod.string(),zod.null()]).optional(),
  "isSegregada": zod.union([zod.boolean(),zod.null()]).optional(),
  "checklist": zod.union([zod.object({
  "temperaturaTrunk": zod.union([zod.number(),zod.null()]).optional(),
  "temperaturaProduto": zod.union([zod.number(),zod.null()]).optional(),
  "observacoes": zod.union([zod.string(),zod.null()]).optional()
}),zod.null()]).optional(),
  "items": zod.array(zod.object({
  "id": zod.string(),
  "codigoProduto": zod.string(),
  "descricao": zod.string(),
  "caixasEsperadas": zod.number().min(finalizarDemandaCompactaBodyItemsItemCaixasEsperadasMin).max(finalizarDemandaCompactaBodyItemsItemCaixasEsperadasMax).optional(),
  "unidadesEsperadas": zod.number().min(finalizarDemandaCompactaBodyItemsItemUnidadesEsperadasMin).max(finalizarDemandaCompactaBodyItemsItemUnidadesEsperadasMax).optional(),
  "isReentrega": zod.boolean().optional(),
  "conferencias": zod.array(zod.object({
  "id": zod.string(),
  "codigoProduto": zod.string(),
  "lote": zod.union([zod.string(),zod.null()]).optional(),
  "caixas": zod.number().min(finalizarDemandaCompactaBodyItemsItemConferenciasItemCaixasMin).max(finalizarDemandaCompactaBodyItemsItemConferenciasItemCaixasMax).optional(),
  "unidades": zod.number().min(finalizarDemandaCompactaBodyItemsItemConferenciasItemUnidadesMin).max(finalizarDemandaCompactaBodyItemsItemConferenciasItemUnidadesMax).optional()
})),
  "anomalias": zod.array(zod.object({
  "id": zod.string(),
  "natureza": zod.union([zod.string(),zod.null()]).optional(),
  "tipo": zod.string(),
  "causa": zod.union([zod.string(),zod.null()]).optional(),
  "fotos": zod.array(zod.string()),
  "observacoes": zod.union([zod.string(),zod.null()]).optional(),
  "caixasDanificadas": zod.number().min(finalizarDemandaCompactaBodyItemsItemAnomaliasItemCaixasDanificadasMin).max(finalizarDemandaCompactaBodyItemsItemAnomaliasItemCaixasDanificadasMax).optional(),
  "unidadesDanificadas": zod.number().min(finalizarDemandaCompactaBodyItemsItemAnomaliasItemUnidadesDanificadasMin).max(finalizarDemandaCompactaBodyItemsItemAnomaliasItemUnidadesDanificadasMax).optional(),
  "lote": zod.string()
})),
  "extra": zod.boolean().optional()
})),
  "sync": zod.enum(['sync', 'pending', 'error', 'not_sync'])
})

